// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drivers.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Driver struct {
	// Types that are valid to be assigned to Driver:
	//	*Driver_HttpBasicAuth
	//	*Driver_HttpNoAuth
	//	*Driver_HttpAuth
	//	*Driver_Mysql
	//	*Driver_AuroraMysql
	//	*Driver_Clustrix
	//	*Driver_Maria
	//	*Driver_Memsql
	//	*Driver_Athena
	Driver               isDriver_Driver `protobuf_oneof:"driver"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Driver) Reset()         { *m = Driver{} }
func (m *Driver) String() string { return proto.CompactTextString(m) }
func (*Driver) ProtoMessage()    {}
func (*Driver) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{0}
}

func (m *Driver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Driver.Unmarshal(m, b)
}
func (m *Driver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Driver.Marshal(b, m, deterministic)
}
func (m *Driver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Driver.Merge(m, src)
}
func (m *Driver) XXX_Size() int {
	return xxx_messageInfo_Driver.Size(m)
}
func (m *Driver) XXX_DiscardUnknown() {
	xxx_messageInfo_Driver.DiscardUnknown(m)
}

var xxx_messageInfo_Driver proto.InternalMessageInfo

type isDriver_Driver interface {
	isDriver_Driver()
}

type Driver_HttpBasicAuth struct {
	HttpBasicAuth *HTTPBasicAuth `protobuf:"bytes,448320780,opt,name=http_basic_auth,json=httpBasicAuth,proto3,oneof"`
}

type Driver_HttpNoAuth struct {
	HttpNoAuth *HTTPNoAuth `protobuf:"bytes,435770653,opt,name=http_no_auth,json=httpNoAuth,proto3,oneof"`
}

type Driver_HttpAuth struct {
	HttpAuth *HTTPAuth `protobuf:"bytes,224436590,opt,name=http_auth,json=httpAuth,proto3,oneof"`
}

type Driver_Mysql struct {
	Mysql *Mysql `protobuf:"bytes,386203715,opt,name=mysql,proto3,oneof"`
}

type Driver_AuroraMysql struct {
	AuroraMysql *AuroraMysql `protobuf:"bytes,18289005,opt,name=aurora_mysql,json=auroraMysql,proto3,oneof"`
}

type Driver_Clustrix struct {
	Clustrix *Clustrix `protobuf:"bytes,532386964,opt,name=clustrix,proto3,oneof"`
}

type Driver_Maria struct {
	Maria *Maria `protobuf:"bytes,466202260,opt,name=maria,proto3,oneof"`
}

type Driver_Memsql struct {
	Memsql *Memsql `protobuf:"bytes,269999277,opt,name=memsql,proto3,oneof"`
}

type Driver_Athena struct {
	Athena *Athena `protobuf:"bytes,86524680,opt,name=athena,proto3,oneof"`
}

func (*Driver_HttpBasicAuth) isDriver_Driver() {}

func (*Driver_HttpNoAuth) isDriver_Driver() {}

func (*Driver_HttpAuth) isDriver_Driver() {}

func (*Driver_Mysql) isDriver_Driver() {}

func (*Driver_AuroraMysql) isDriver_Driver() {}

func (*Driver_Clustrix) isDriver_Driver() {}

func (*Driver_Maria) isDriver_Driver() {}

func (*Driver_Memsql) isDriver_Driver() {}

func (*Driver_Athena) isDriver_Driver() {}

func (m *Driver) GetDriver() isDriver_Driver {
	if m != nil {
		return m.Driver
	}
	return nil
}

func (m *Driver) GetHttpBasicAuth() *HTTPBasicAuth {
	if x, ok := m.GetDriver().(*Driver_HttpBasicAuth); ok {
		return x.HttpBasicAuth
	}
	return nil
}

func (m *Driver) GetHttpNoAuth() *HTTPNoAuth {
	if x, ok := m.GetDriver().(*Driver_HttpNoAuth); ok {
		return x.HttpNoAuth
	}
	return nil
}

func (m *Driver) GetHttpAuth() *HTTPAuth {
	if x, ok := m.GetDriver().(*Driver_HttpAuth); ok {
		return x.HttpAuth
	}
	return nil
}

func (m *Driver) GetMysql() *Mysql {
	if x, ok := m.GetDriver().(*Driver_Mysql); ok {
		return x.Mysql
	}
	return nil
}

func (m *Driver) GetAuroraMysql() *AuroraMysql {
	if x, ok := m.GetDriver().(*Driver_AuroraMysql); ok {
		return x.AuroraMysql
	}
	return nil
}

func (m *Driver) GetClustrix() *Clustrix {
	if x, ok := m.GetDriver().(*Driver_Clustrix); ok {
		return x.Clustrix
	}
	return nil
}

func (m *Driver) GetMaria() *Maria {
	if x, ok := m.GetDriver().(*Driver_Maria); ok {
		return x.Maria
	}
	return nil
}

func (m *Driver) GetMemsql() *Memsql {
	if x, ok := m.GetDriver().(*Driver_Memsql); ok {
		return x.Memsql
	}
	return nil
}

func (m *Driver) GetAthena() *Athena {
	if x, ok := m.GetDriver().(*Driver_Athena); ok {
		return x.Athena
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Driver) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Driver_HttpBasicAuth)(nil),
		(*Driver_HttpNoAuth)(nil),
		(*Driver_HttpAuth)(nil),
		(*Driver_Mysql)(nil),
		(*Driver_AuroraMysql)(nil),
		(*Driver_Clustrix)(nil),
		(*Driver_Maria)(nil),
		(*Driver_Memsql)(nil),
		(*Driver_Athena)(nil),
	}
}

type HTTPBasicAuth struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,5,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,6,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,7,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPBasicAuth) Reset()         { *m = HTTPBasicAuth{} }
func (m *HTTPBasicAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPBasicAuth) ProtoMessage()    {}
func (*HTTPBasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{1}
}

func (m *HTTPBasicAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPBasicAuth.Unmarshal(m, b)
}
func (m *HTTPBasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPBasicAuth.Marshal(b, m, deterministic)
}
func (m *HTTPBasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPBasicAuth.Merge(m, src)
}
func (m *HTTPBasicAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPBasicAuth.Size(m)
}
func (m *HTTPBasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPBasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPBasicAuth proto.InternalMessageInfo

func (m *HTTPBasicAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPBasicAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPBasicAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *HTTPBasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *HTTPBasicAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPBasicAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPBasicAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type HTTPNoAuth struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,3,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,4,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,5,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPNoAuth) Reset()         { *m = HTTPNoAuth{} }
func (m *HTTPNoAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPNoAuth) ProtoMessage()    {}
func (*HTTPNoAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{2}
}

func (m *HTTPNoAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPNoAuth.Unmarshal(m, b)
}
func (m *HTTPNoAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPNoAuth.Marshal(b, m, deterministic)
}
func (m *HTTPNoAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPNoAuth.Merge(m, src)
}
func (m *HTTPNoAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPNoAuth.Size(m)
}
func (m *HTTPNoAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPNoAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPNoAuth proto.InternalMessageInfo

func (m *HTTPNoAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPNoAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPNoAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPNoAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPNoAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type HTTPAuth struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	AuthHeader           string   `protobuf:"bytes,3,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,4,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,5,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,6,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPAuth) Reset()         { *m = HTTPAuth{} }
func (m *HTTPAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPAuth) ProtoMessage()    {}
func (*HTTPAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{3}
}

func (m *HTTPAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPAuth.Unmarshal(m, b)
}
func (m *HTTPAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPAuth.Marshal(b, m, deterministic)
}
func (m *HTTPAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPAuth.Merge(m, src)
}
func (m *HTTPAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPAuth.Size(m)
}
func (m *HTTPAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPAuth proto.InternalMessageInfo

func (m *HTTPAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPAuth) GetAuthHeader() string {
	if m != nil {
		return m.AuthHeader
	}
	return ""
}

func (m *HTTPAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type Mysql struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mysql) Reset()         { *m = Mysql{} }
func (m *Mysql) String() string { return proto.CompactTextString(m) }
func (*Mysql) ProtoMessage()    {}
func (*Mysql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{4}
}

func (m *Mysql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mysql.Unmarshal(m, b)
}
func (m *Mysql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mysql.Marshal(b, m, deterministic)
}
func (m *Mysql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mysql.Merge(m, src)
}
func (m *Mysql) XXX_Size() int {
	return xxx_messageInfo_Mysql.Size(m)
}
func (m *Mysql) XXX_DiscardUnknown() {
	xxx_messageInfo_Mysql.DiscardUnknown(m)
}

var xxx_messageInfo_Mysql proto.InternalMessageInfo

func (m *Mysql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Mysql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Mysql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Mysql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Mysql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type AuroraMysql struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuroraMysql) Reset()         { *m = AuroraMysql{} }
func (m *AuroraMysql) String() string { return proto.CompactTextString(m) }
func (*AuroraMysql) ProtoMessage()    {}
func (*AuroraMysql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{5}
}

func (m *AuroraMysql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuroraMysql.Unmarshal(m, b)
}
func (m *AuroraMysql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuroraMysql.Marshal(b, m, deterministic)
}
func (m *AuroraMysql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuroraMysql.Merge(m, src)
}
func (m *AuroraMysql) XXX_Size() int {
	return xxx_messageInfo_AuroraMysql.Size(m)
}
func (m *AuroraMysql) XXX_DiscardUnknown() {
	xxx_messageInfo_AuroraMysql.DiscardUnknown(m)
}

var xxx_messageInfo_AuroraMysql proto.InternalMessageInfo

func (m *AuroraMysql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AuroraMysql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuroraMysql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuroraMysql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *AuroraMysql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Clustrix struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clustrix) Reset()         { *m = Clustrix{} }
func (m *Clustrix) String() string { return proto.CompactTextString(m) }
func (*Clustrix) ProtoMessage()    {}
func (*Clustrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{6}
}

func (m *Clustrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clustrix.Unmarshal(m, b)
}
func (m *Clustrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clustrix.Marshal(b, m, deterministic)
}
func (m *Clustrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clustrix.Merge(m, src)
}
func (m *Clustrix) XXX_Size() int {
	return xxx_messageInfo_Clustrix.Size(m)
}
func (m *Clustrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Clustrix.DiscardUnknown(m)
}

var xxx_messageInfo_Clustrix proto.InternalMessageInfo

func (m *Clustrix) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Clustrix) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Clustrix) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Clustrix) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Clustrix) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Maria struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Maria) Reset()         { *m = Maria{} }
func (m *Maria) String() string { return proto.CompactTextString(m) }
func (*Maria) ProtoMessage()    {}
func (*Maria) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{7}
}

func (m *Maria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Maria.Unmarshal(m, b)
}
func (m *Maria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Maria.Marshal(b, m, deterministic)
}
func (m *Maria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Maria.Merge(m, src)
}
func (m *Maria) XXX_Size() int {
	return xxx_messageInfo_Maria.Size(m)
}
func (m *Maria) XXX_DiscardUnknown() {
	xxx_messageInfo_Maria.DiscardUnknown(m)
}

var xxx_messageInfo_Maria proto.InternalMessageInfo

func (m *Maria) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Maria) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Maria) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Maria) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Maria) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Memsql struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memsql) Reset()         { *m = Memsql{} }
func (m *Memsql) String() string { return proto.CompactTextString(m) }
func (*Memsql) ProtoMessage()    {}
func (*Memsql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{8}
}

func (m *Memsql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memsql.Unmarshal(m, b)
}
func (m *Memsql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memsql.Marshal(b, m, deterministic)
}
func (m *Memsql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memsql.Merge(m, src)
}
func (m *Memsql) XXX_Size() int {
	return xxx_messageInfo_Memsql.Size(m)
}
func (m *Memsql) XXX_DiscardUnknown() {
	xxx_messageInfo_Memsql.DiscardUnknown(m)
}

var xxx_messageInfo_Memsql proto.InternalMessageInfo

func (m *Memsql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Memsql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Memsql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Memsql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Memsql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Athena struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,2,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Output               string   `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Athena) Reset()         { *m = Athena{} }
func (m *Athena) String() string { return proto.CompactTextString(m) }
func (*Athena) ProtoMessage()    {}
func (*Athena) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{9}
}

func (m *Athena) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Athena.Unmarshal(m, b)
}
func (m *Athena) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Athena.Marshal(b, m, deterministic)
}
func (m *Athena) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Athena.Merge(m, src)
}
func (m *Athena) XXX_Size() int {
	return xxx_messageInfo_Athena.Size(m)
}
func (m *Athena) XXX_DiscardUnknown() {
	xxx_messageInfo_Athena.DiscardUnknown(m)
}

var xxx_messageInfo_Athena proto.InternalMessageInfo

func (m *Athena) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *Athena) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *Athena) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Athena) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*Driver)(nil), "v1.Driver")
	proto.RegisterType((*HTTPBasicAuth)(nil), "v1.HTTPBasicAuth")
	proto.RegisterType((*HTTPNoAuth)(nil), "v1.HTTPNoAuth")
	proto.RegisterType((*HTTPAuth)(nil), "v1.HTTPAuth")
	proto.RegisterType((*Mysql)(nil), "v1.Mysql")
	proto.RegisterType((*AuroraMysql)(nil), "v1.AuroraMysql")
	proto.RegisterType((*Clustrix)(nil), "v1.Clustrix")
	proto.RegisterType((*Maria)(nil), "v1.Maria")
	proto.RegisterType((*Memsql)(nil), "v1.Memsql")
	proto.RegisterType((*Athena)(nil), "v1.Athena")
}

func init() { proto.RegisterFile("drivers.proto", fileDescriptor_81dfd49b5b303fb4) }

var fileDescriptor_81dfd49b5b303fb4 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x96, 0x4d, 0x68, 0x03, 0x45,
	0x14, 0xc7, 0xbb, 0xf9, 0xd8, 0x6e, 0x5e, 0x12, 0xd3, 0x8e, 0x97, 0xa5, 0xf4, 0x20, 0x01, 0xfb,
	0x81, 0x26, 0x6d, 0xad, 0xb6, 0xd0, 0x8b, 0x26, 0x7a, 0x08, 0x88, 0x52, 0x42, 0xef, 0x61, 0xb2,
	0x19, 0xb3, 0x4b, 0x76, 0x77, 0xd6, 0x99, 0xd9, 0xd6, 0xde, 0x8a, 0x88, 0x78, 0xf0, 0x54, 0x7a,
	0xf5, 0xa0, 0x07, 0xd1, 0x82, 0x28, 0xf4, 0xa2, 0x57, 0x3d, 0x7a, 0x10, 0x0f, 0xe2, 0xa5, 0xb5,
	0xa0, 0x78, 0xb4, 0x07, 0xbd, 0x88, 0x20, 0xc8, 0xcc, 0xec, 0x36, 0x89, 0x09, 0x62, 0x0a, 0xbd,
	0xe4, 0xb6, 0xfb, 0xfe, 0xbf, 0x7f, 0xf6, 0xbd, 0x97, 0x7d, 0x6f, 0x07, 0xca, 0x3d, 0xe6, 0x1d,
	0x13, 0xc6, 0xeb, 0x11, 0xa3, 0x82, 0xa2, 0xcc, 0xf1, 0xce, 0xca, 0xb3, 0xea, 0xd2, 0xa9, 0xf5,
	0x49, 0x58, 0xe3, 0x27, 0xb8, 0xdf, 0x27, 0x6c, 0x8b, 0x46, 0xc2, 0xa3, 0x21, 0xdf, 0xc2, 0x61,
	0x48, 0x05, 0x56, 0xd7, 0xda, 0xb1, 0x52, 0x4e, 0x24, 0x7d, 0x5b, 0xfd, 0x3e, 0x0b, 0xe6, 0x2b,
	0xea, 0x27, 0xd1, 0x8b, 0x50, 0x71, 0x85, 0x88, 0x3a, 0x5d, 0xcc, 0x3d, 0xa7, 0x83, 0x63, 0xe1,
	0xda, 0xef, 0x5f, 0xfe, 0xf2, 0x83, 0xf1, 0x94, 0xb1, 0x51, 0x7c, 0x6e, 0xb9, 0x7e, 0xbc, 0x53,
	0x6f, 0x1d, 0x1d, 0x1d, 0x36, 0xa5, 0xda, 0x88, 0x85, 0xdb, 0x5a, 0x68, 0x97, 0x25, 0x7f, 0x1f,
	0x40, 0x7b, 0x50, 0x52, 0x3f, 0x10, 0x52, 0xed, 0xfe, 0xe0, 0xf2, 0xd7, 0xef, 0xb4, 0xfb, 0x89,
	0xd4, 0xfd, 0x3a, 0x4d, 0xac, 0x20, 0x49, 0x7d, 0x87, 0xea, 0x50, 0x50, 0x3e, 0x65, 0xba, 0xfb,
	0xfa, 0xed, 0x81, 0xf2, 0x94, 0x52, 0x4f, 0xe2, 0xb0, 0x24, 0xa3, 0xf8, 0xa7, 0x21, 0x1f, 0x9c,
	0xf2, 0x37, 0x7d, 0xfb, 0x9b, 0xb3, 0x8b, 0x2f, 0xf5, 0x03, 0x0a, 0x12, 0x7e, 0x4d, 0x06, 0x5b,
	0x0b, 0x6d, 0xad, 0xa2, 0x7d, 0x28, 0xe1, 0x98, 0x51, 0x86, 0x3b, 0x9a, 0xfe, 0xed, 0xa3, 0x6b,
	0x4b, 0xc1, 0x15, 0x09, 0x37, 0x94, 0x94, 0x5a, 0x8a, 0x78, 0x78, 0x8b, 0xea, 0x60, 0x39, 0x7e,
	0xcc, 0x05, 0xf3, 0xde, 0xb2, 0x2f, 0x3e, 0xbd, 0xfb, 0xdb, 0x18, 0xe6, 0xf3, 0x72, 0x12, 0x97,
	0xf9, 0xa4, 0x8c, 0xca, 0x07, 0x33, 0x0f, 0xdb, 0x17, 0x37, 0x1f, 0xff, 0x34, 0x9a, 0x8f, 0x0c,
	0xaa, 0x7c, 0xe4, 0x05, 0xda, 0x00, 0x33, 0x20, 0x81, 0xcc, 0xe4, 0xb3, 0xaf, 0x6e, 0xcf, 0x34,
	0x07, 0x8a, 0x53, 0xd1, 0xd6, 0x42, 0x3b, 0xd1, 0xd1, 0x3a, 0x98, 0x58, 0xb8, 0x24, 0xc4, 0xf6,
	0x7b, 0xef, 0x7e, 0xb8, 0x39, 0x04, 0x1b, 0x2a, 0x28, 0x41, 0x2d, 0x1f, 0xc0, 0x5f, 0x7f, 0x5e,
	0x2d, 0xe6, 0x3f, 0xf9, 0xe3, 0x6a, 0xd1, 0x68, 0x5a, 0x60, 0xea, 0x77, 0xa3, 0xfa, 0x63, 0x06,
	0xca, 0x63, 0x7f, 0x15, 0x5a, 0x85, 0x6c, 0xcc, 0x7c, 0x5b, 0x3e, 0xb3, 0xd0, 0x84, 0xdf, 0xa5,
	0xe9, 0x0b, 0x69, 0x6a, 0xcb, 0x30, 0x7a, 0x01, 0x96, 0x5c, 0x82, 0x7d, 0xe1, 0x3a, 0x2e, 0x71,
	0x06, 0x9d, 0x08, 0x0b, 0xd7, 0xce, 0x4c, 0xa0, 0x95, 0x11, 0xe6, 0x10, 0x0b, 0x17, 0xad, 0x81,
	0x15, 0x73, 0xc2, 0x42, 0x1c, 0x10, 0x3b, 0x3b, 0x81, 0xdf, 0x6b, 0x92, 0x8b, 0x30, 0xe7, 0x27,
	0x94, 0xf5, 0xec, 0xdc, 0x24, 0x97, 0x6a, 0x68, 0x1f, 0x96, 0x5d, 0x82, 0x7b, 0x84, 0xf1, 0x4e,
	0xd7, 0xc7, 0xce, 0xc0, 0xf7, 0xb8, 0xb0, 0xf3, 0x13, 0x86, 0xa5, 0x04, 0x6a, 0xa6, 0x0c, 0xaa,
	0x41, 0xa9, 0x47, 0xde, 0xc0, 0xb1, 0x2f, 0x74, 0xee, 0xe6, 0x84, 0xa7, 0x98, 0xe8, 0x2a, 0xef,
	0x1a, 0x14, 0x78, 0xdc, 0xed, 0xd1, 0x00, 0x7b, 0xa1, 0xbd, 0xa8, 0xd8, 0xca, 0x79, 0x23, 0xf3,
	0x92, 0x31, 0x62, 0x18, 0x12, 0xa3, 0x3d, 0xae, 0xbe, 0x93, 0x01, 0x18, 0xbe, 0xc6, 0x8f, 0xd3,
	0xd6, 0xa9, 0x6d, 0xc8, 0x3e, 0xa0, 0x0d, 0xb9, 0x19, 0xda, 0x90, 0x9f, 0xa9, 0x0d, 0x9f, 0x67,
	0xc0, 0x4a, 0x27, 0xf3, 0x71, 0x9a, 0xf0, 0x0c, 0x14, 0xe5, 0x36, 0xe8, 0xe8, 0x22, 0xa7, 0x94,
	0x0f, 0x52, 0x6e, 0x29, 0x75, 0x7a, 0xc7, 0x72, 0x0f, 0xe8, 0x58, 0x7e, 0x86, 0x8e, 0x99, 0x33,
	0x75, 0xec, 0xda, 0x80, 0xbc, 0x5e, 0x2e, 0x6b, 0x60, 0xb9, 0x94, 0x0b, 0x35, 0x35, 0x93, 0x3d,
	0xbb, 0xd7, 0xc6, 0xa6, 0x2b, 0xf3, 0x3f, 0xa7, 0x2b, 0xfb, 0x1f, 0xd3, 0xb5, 0x06, 0x56, 0x0f,
	0x0b, 0xdc, 0xc5, 0x9c, 0x4c, 0x9b, 0xc2, 0x54, 0x43, 0xeb, 0x90, 0x8b, 0x28, 0xd3, 0x83, 0x97,
	0x6f, 0x3e, 0x79, 0xde, 0x30, 0x0f, 0x72, 0xbb, 0xbb, 0xdb, 0x7b, 0x23, 0xb0, 0x02, 0xc6, 0xca,
	0xfb, 0xd9, 0x80, 0xe2, 0xc8, 0x42, 0x9d, 0xcf, 0x22, 0x6f, 0x0d, 0xb0, 0xd2, 0xfd, 0x3f, 0x9f,
	0x15, 0xaa, 0xb7, 0x54, 0x7d, 0xab, 0xe6, 0xb2, 0xbc, 0x1b, 0x03, 0x4c, 0xfd, 0xad, 0x9d, 0xcf,
	0xfa, 0xbe, 0x35, 0xc0, 0xd4, 0x47, 0x04, 0xb4, 0x09, 0x80, 0x1d, 0x87, 0x70, 0xde, 0x19, 0x90,
	0xd3, 0x29, 0x15, 0x16, 0xb4, 0xfa, 0x2a, 0x39, 0x45, 0xcf, 0x43, 0x85, 0x13, 0x87, 0x11, 0xd1,
	0x48, 0x43, 0xd3, 0x16, 0xf4, 0xbf, 0x10, 0xb4, 0x0d, 0x26, 0x23, 0x7d, 0x8f, 0x86, 0x49, 0xb9,
	0xf6, 0x79, 0xa3, 0x78, 0x50, 0x88, 0x79, 0x8d, 0x60, 0x2e, 0x6a, 0x3b, 0x23, 0xd6, 0x84, 0x43,
	0x55, 0x30, 0x69, 0x2c, 0xa2, 0x78, 0xda, 0x6a, 0x4e, 0x94, 0xb1, 0xf3, 0xcc, 0x16, 0xac, 0x3a,
	0x34, 0xa8, 0x73, 0xc1, 0x68, 0xd8, 0xef, 0x05, 0x75, 0x1c, 0x79, 0xf2, 0x0c, 0x14, 0xf9, 0x71,
	0xd0, 0xf5, 0xc2, 0x7e, 0xb3, 0xa2, 0x8f, 0xad, 0xfc, 0x30, 0x09, 0x74, 0x4d, 0x75, 0xa2, 0xdd,
	0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe8, 0x77, 0xfe, 0x23, 0x0b, 0x00, 0x00,
}
