// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drivers.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Resource is a server or service which clients connect to through relays.
type Resource struct {
	// Types that are valid to be assigned to Resource:
	//	*Resource_Redis
	//	*Resource_ElasticacheRedis
	//	*Resource_Kubernetes
	//	*Resource_KubernetesBasicAuth
	//	*Resource_AmazonEks
	//	*Resource_GoogleGke
	//	*Resource_Ssh
	//	*Resource_HttpBasicAuth
	//	*Resource_HttpNoAuth
	//	*Resource_HttpAuth
	//	*Resource_Mysql
	//	*Resource_AuroraMysql
	//	*Resource_Clustrix
	//	*Resource_Maria
	//	*Resource_Memsql
	//	*Resource_Athena
	Resource             isResource_Resource `protobuf_oneof:"resource"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

type isResource_Resource interface {
	isResource_Resource()
}

type Resource_Redis struct {
	Redis *Redis `protobuf:"bytes,138869556,opt,name=redis,proto3,oneof"`
}

type Resource_ElasticacheRedis struct {
	ElasticacheRedis *ElasticacheRedis `protobuf:"bytes,28044999,opt,name=elasticache_redis,json=elasticacheRedis,proto3,oneof"`
}

type Resource_Kubernetes struct {
	Kubernetes *Kubernetes `protobuf:"bytes,231451540,opt,name=kubernetes,proto3,oneof"`
}

type Resource_KubernetesBasicAuth struct {
	KubernetesBasicAuth *KubernetesBasicAuth `protobuf:"bytes,471837167,opt,name=kubernetes_basic_auth,json=kubernetesBasicAuth,proto3,oneof"`
}

type Resource_AmazonEks struct {
	AmazonEks *AmazonEKS `protobuf:"bytes,144724720,opt,name=amazon_eks,json=amazonEks,proto3,oneof"`
}

type Resource_GoogleGke struct {
	GoogleGke *GoogleGKE `protobuf:"bytes,138696469,opt,name=google_gke,json=googleGke,proto3,oneof"`
}

type Resource_Ssh struct {
	Ssh *SSH `protobuf:"bytes,257251967,opt,name=ssh,proto3,oneof"`
}

type Resource_HttpBasicAuth struct {
	HttpBasicAuth *HTTPBasicAuth `protobuf:"bytes,448320780,opt,name=http_basic_auth,json=httpBasicAuth,proto3,oneof"`
}

type Resource_HttpNoAuth struct {
	HttpNoAuth *HTTPNoAuth `protobuf:"bytes,435770653,opt,name=http_no_auth,json=httpNoAuth,proto3,oneof"`
}

type Resource_HttpAuth struct {
	HttpAuth *HTTPAuth `protobuf:"bytes,224436590,opt,name=http_auth,json=httpAuth,proto3,oneof"`
}

type Resource_Mysql struct {
	Mysql *Mysql `protobuf:"bytes,386203715,opt,name=mysql,proto3,oneof"`
}

type Resource_AuroraMysql struct {
	AuroraMysql *AuroraMysql `protobuf:"bytes,18289005,opt,name=aurora_mysql,json=auroraMysql,proto3,oneof"`
}

type Resource_Clustrix struct {
	Clustrix *Clustrix `protobuf:"bytes,532386964,opt,name=clustrix,proto3,oneof"`
}

type Resource_Maria struct {
	Maria *Maria `protobuf:"bytes,466202260,opt,name=maria,proto3,oneof"`
}

type Resource_Memsql struct {
	Memsql *Memsql `protobuf:"bytes,269999277,opt,name=memsql,proto3,oneof"`
}

type Resource_Athena struct {
	Athena *Athena `protobuf:"bytes,86524680,opt,name=athena,proto3,oneof"`
}

func (*Resource_Redis) isResource_Resource() {}

func (*Resource_ElasticacheRedis) isResource_Resource() {}

func (*Resource_Kubernetes) isResource_Resource() {}

func (*Resource_KubernetesBasicAuth) isResource_Resource() {}

func (*Resource_AmazonEks) isResource_Resource() {}

func (*Resource_GoogleGke) isResource_Resource() {}

func (*Resource_Ssh) isResource_Resource() {}

func (*Resource_HttpBasicAuth) isResource_Resource() {}

func (*Resource_HttpNoAuth) isResource_Resource() {}

func (*Resource_HttpAuth) isResource_Resource() {}

func (*Resource_Mysql) isResource_Resource() {}

func (*Resource_AuroraMysql) isResource_Resource() {}

func (*Resource_Clustrix) isResource_Resource() {}

func (*Resource_Maria) isResource_Resource() {}

func (*Resource_Memsql) isResource_Resource() {}

func (*Resource_Athena) isResource_Resource() {}

func (m *Resource) GetResource() isResource_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *Resource) GetRedis() *Redis {
	if x, ok := m.GetResource().(*Resource_Redis); ok {
		return x.Redis
	}
	return nil
}

func (m *Resource) GetElasticacheRedis() *ElasticacheRedis {
	if x, ok := m.GetResource().(*Resource_ElasticacheRedis); ok {
		return x.ElasticacheRedis
	}
	return nil
}

func (m *Resource) GetKubernetes() *Kubernetes {
	if x, ok := m.GetResource().(*Resource_Kubernetes); ok {
		return x.Kubernetes
	}
	return nil
}

func (m *Resource) GetKubernetesBasicAuth() *KubernetesBasicAuth {
	if x, ok := m.GetResource().(*Resource_KubernetesBasicAuth); ok {
		return x.KubernetesBasicAuth
	}
	return nil
}

func (m *Resource) GetAmazonEks() *AmazonEKS {
	if x, ok := m.GetResource().(*Resource_AmazonEks); ok {
		return x.AmazonEks
	}
	return nil
}

func (m *Resource) GetGoogleGke() *GoogleGKE {
	if x, ok := m.GetResource().(*Resource_GoogleGke); ok {
		return x.GoogleGke
	}
	return nil
}

func (m *Resource) GetSsh() *SSH {
	if x, ok := m.GetResource().(*Resource_Ssh); ok {
		return x.Ssh
	}
	return nil
}

func (m *Resource) GetHttpBasicAuth() *HTTPBasicAuth {
	if x, ok := m.GetResource().(*Resource_HttpBasicAuth); ok {
		return x.HttpBasicAuth
	}
	return nil
}

func (m *Resource) GetHttpNoAuth() *HTTPNoAuth {
	if x, ok := m.GetResource().(*Resource_HttpNoAuth); ok {
		return x.HttpNoAuth
	}
	return nil
}

func (m *Resource) GetHttpAuth() *HTTPAuth {
	if x, ok := m.GetResource().(*Resource_HttpAuth); ok {
		return x.HttpAuth
	}
	return nil
}

func (m *Resource) GetMysql() *Mysql {
	if x, ok := m.GetResource().(*Resource_Mysql); ok {
		return x.Mysql
	}
	return nil
}

func (m *Resource) GetAuroraMysql() *AuroraMysql {
	if x, ok := m.GetResource().(*Resource_AuroraMysql); ok {
		return x.AuroraMysql
	}
	return nil
}

func (m *Resource) GetClustrix() *Clustrix {
	if x, ok := m.GetResource().(*Resource_Clustrix); ok {
		return x.Clustrix
	}
	return nil
}

func (m *Resource) GetMaria() *Maria {
	if x, ok := m.GetResource().(*Resource_Maria); ok {
		return x.Maria
	}
	return nil
}

func (m *Resource) GetMemsql() *Memsql {
	if x, ok := m.GetResource().(*Resource_Memsql); ok {
		return x.Memsql
	}
	return nil
}

func (m *Resource) GetAthena() *Athena {
	if x, ok := m.GetResource().(*Resource_Athena); ok {
		return x.Athena
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Resource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Resource_Redis)(nil),
		(*Resource_ElasticacheRedis)(nil),
		(*Resource_Kubernetes)(nil),
		(*Resource_KubernetesBasicAuth)(nil),
		(*Resource_AmazonEks)(nil),
		(*Resource_GoogleGke)(nil),
		(*Resource_Ssh)(nil),
		(*Resource_HttpBasicAuth)(nil),
		(*Resource_HttpNoAuth)(nil),
		(*Resource_HttpAuth)(nil),
		(*Resource_Mysql)(nil),
		(*Resource_AuroraMysql)(nil),
		(*Resource_Clustrix)(nil),
		(*Resource_Maria)(nil),
		(*Resource_Memsql)(nil),
		(*Resource_Athena)(nil),
	}
}

type Redis struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PortOverride         int32    `protobuf:"varint,2,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redis) Reset()         { *m = Redis{} }
func (m *Redis) String() string { return proto.CompactTextString(m) }
func (*Redis) ProtoMessage()    {}
func (*Redis) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{1}
}

func (m *Redis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redis.Unmarshal(m, b)
}
func (m *Redis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redis.Marshal(b, m, deterministic)
}
func (m *Redis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redis.Merge(m, src)
}
func (m *Redis) XXX_Size() int {
	return xxx_messageInfo_Redis.Size(m)
}
func (m *Redis) XXX_DiscardUnknown() {
	xxx_messageInfo_Redis.DiscardUnknown(m)
}

var xxx_messageInfo_Redis proto.InternalMessageInfo

func (m *Redis) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Redis) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Redis) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Redis) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Redis) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Redis) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Redis) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ElasticacheRedis struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PortOverride         int32    `protobuf:"varint,2,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	TlsRequired          bool     `protobuf:"varint,5,opt,name=tls_required,json=tlsRequired,proto3" json:"tls_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ElasticacheRedis) Reset()         { *m = ElasticacheRedis{} }
func (m *ElasticacheRedis) String() string { return proto.CompactTextString(m) }
func (*ElasticacheRedis) ProtoMessage()    {}
func (*ElasticacheRedis) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{2}
}

func (m *ElasticacheRedis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ElasticacheRedis.Unmarshal(m, b)
}
func (m *ElasticacheRedis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ElasticacheRedis.Marshal(b, m, deterministic)
}
func (m *ElasticacheRedis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ElasticacheRedis.Merge(m, src)
}
func (m *ElasticacheRedis) XXX_Size() int {
	return xxx_messageInfo_ElasticacheRedis.Size(m)
}
func (m *ElasticacheRedis) XXX_DiscardUnknown() {
	xxx_messageInfo_ElasticacheRedis.DiscardUnknown(m)
}

var xxx_messageInfo_ElasticacheRedis proto.InternalMessageInfo

func (m *ElasticacheRedis) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ElasticacheRedis) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ElasticacheRedis) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *ElasticacheRedis) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ElasticacheRedis) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *ElasticacheRedis) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ElasticacheRedis) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ElasticacheRedis) GetTlsRequired() bool {
	if m != nil {
		return m.TlsRequired
	}
	return false
}

type Kubernetes struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	CertificateAuthority string   `protobuf:"bytes,3,opt,name=certificate_authority,json=certificateAuthority,proto3" json:"certificate_authority,omitempty"`
	ClientCertificate    string   `protobuf:"bytes,4,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	ClientKey            string   `protobuf:"bytes,5,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{3}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Kubernetes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Kubernetes) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Kubernetes) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Kubernetes) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Kubernetes) GetCertificateAuthority() string {
	if m != nil {
		return m.CertificateAuthority
	}
	return ""
}

func (m *Kubernetes) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *Kubernetes) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

type KubernetesBasicAuth struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CertificateAuthority string   `protobuf:"bytes,5,opt,name=certificate_authority,json=certificateAuthority,proto3" json:"certificate_authority,omitempty"`
	ClientCertificate    string   `protobuf:"bytes,6,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	ClientKey            string   `protobuf:"bytes,7,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesBasicAuth) Reset()         { *m = KubernetesBasicAuth{} }
func (m *KubernetesBasicAuth) String() string { return proto.CompactTextString(m) }
func (*KubernetesBasicAuth) ProtoMessage()    {}
func (*KubernetesBasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{4}
}

func (m *KubernetesBasicAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesBasicAuth.Unmarshal(m, b)
}
func (m *KubernetesBasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesBasicAuth.Marshal(b, m, deterministic)
}
func (m *KubernetesBasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesBasicAuth.Merge(m, src)
}
func (m *KubernetesBasicAuth) XXX_Size() int {
	return xxx_messageInfo_KubernetesBasicAuth.Size(m)
}
func (m *KubernetesBasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesBasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesBasicAuth proto.InternalMessageInfo

func (m *KubernetesBasicAuth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KubernetesBasicAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KubernetesBasicAuth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *KubernetesBasicAuth) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *KubernetesBasicAuth) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *KubernetesBasicAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *KubernetesBasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *KubernetesBasicAuth) GetCertificateAuthority() string {
	if m != nil {
		return m.CertificateAuthority
	}
	return ""
}

func (m *KubernetesBasicAuth) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *KubernetesBasicAuth) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

type AmazonEKS struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey            string   `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	CertificateAuthority string   `protobuf:"bytes,4,opt,name=certificate_authority,json=certificateAuthority,proto3" json:"certificate_authority,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	ClusterName          string   `protobuf:"bytes,6,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AmazonEKS) Reset()         { *m = AmazonEKS{} }
func (m *AmazonEKS) String() string { return proto.CompactTextString(m) }
func (*AmazonEKS) ProtoMessage()    {}
func (*AmazonEKS) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{5}
}

func (m *AmazonEKS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AmazonEKS.Unmarshal(m, b)
}
func (m *AmazonEKS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AmazonEKS.Marshal(b, m, deterministic)
}
func (m *AmazonEKS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmazonEKS.Merge(m, src)
}
func (m *AmazonEKS) XXX_Size() int {
	return xxx_messageInfo_AmazonEKS.Size(m)
}
func (m *AmazonEKS) XXX_DiscardUnknown() {
	xxx_messageInfo_AmazonEKS.DiscardUnknown(m)
}

var xxx_messageInfo_AmazonEKS proto.InternalMessageInfo

func (m *AmazonEKS) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AmazonEKS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AmazonEKS) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *AmazonEKS) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *AmazonEKS) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *AmazonEKS) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *AmazonEKS) GetCertificateAuthority() string {
	if m != nil {
		return m.CertificateAuthority
	}
	return ""
}

func (m *AmazonEKS) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AmazonEKS) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type GoogleGKE struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CertificateAuthority string   `protobuf:"bytes,2,opt,name=certificate_authority,json=certificateAuthority,proto3" json:"certificate_authority,omitempty"`
	ServiceAccountKey    string   `protobuf:"bytes,3,opt,name=service_account_key,json=serviceAccountKey,proto3" json:"service_account_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleGKE) Reset()         { *m = GoogleGKE{} }
func (m *GoogleGKE) String() string { return proto.CompactTextString(m) }
func (*GoogleGKE) ProtoMessage()    {}
func (*GoogleGKE) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{6}
}

func (m *GoogleGKE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleGKE.Unmarshal(m, b)
}
func (m *GoogleGKE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleGKE.Marshal(b, m, deterministic)
}
func (m *GoogleGKE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleGKE.Merge(m, src)
}
func (m *GoogleGKE) XXX_Size() int {
	return xxx_messageInfo_GoogleGKE.Size(m)
}
func (m *GoogleGKE) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleGKE.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleGKE proto.InternalMessageInfo

func (m *GoogleGKE) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GoogleGKE) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoogleGKE) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *GoogleGKE) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *GoogleGKE) GetCertificateAuthority() string {
	if m != nil {
		return m.CertificateAuthority
	}
	return ""
}

func (m *GoogleGKE) GetServiceAccountKey() string {
	if m != nil {
		return m.ServiceAccountKey
	}
	return ""
}

type SSH struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	PublicKey            string   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSH) Reset()         { *m = SSH{} }
func (m *SSH) String() string { return proto.CompactTextString(m) }
func (*SSH) ProtoMessage()    {}
func (*SSH) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{7}
}

func (m *SSH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSH.Unmarshal(m, b)
}
func (m *SSH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSH.Marshal(b, m, deterministic)
}
func (m *SSH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSH.Merge(m, src)
}
func (m *SSH) XXX_Size() int {
	return xxx_messageInfo_SSH.Size(m)
}
func (m *SSH) XXX_DiscardUnknown() {
	xxx_messageInfo_SSH.DiscardUnknown(m)
}

var xxx_messageInfo_SSH proto.InternalMessageInfo

func (m *SSH) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SSH) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SSH) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *SSH) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SSH) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SSH) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SSH) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type HTTPBasicAuth struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,5,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,6,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,7,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPBasicAuth) Reset()         { *m = HTTPBasicAuth{} }
func (m *HTTPBasicAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPBasicAuth) ProtoMessage()    {}
func (*HTTPBasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{8}
}

func (m *HTTPBasicAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPBasicAuth.Unmarshal(m, b)
}
func (m *HTTPBasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPBasicAuth.Marshal(b, m, deterministic)
}
func (m *HTTPBasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPBasicAuth.Merge(m, src)
}
func (m *HTTPBasicAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPBasicAuth.Size(m)
}
func (m *HTTPBasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPBasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPBasicAuth proto.InternalMessageInfo

func (m *HTTPBasicAuth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HTTPBasicAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HTTPBasicAuth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *HTTPBasicAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPBasicAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPBasicAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *HTTPBasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *HTTPBasicAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPBasicAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPBasicAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type HTTPNoAuth struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,3,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,4,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,5,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPNoAuth) Reset()         { *m = HTTPNoAuth{} }
func (m *HTTPNoAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPNoAuth) ProtoMessage()    {}
func (*HTTPNoAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{9}
}

func (m *HTTPNoAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPNoAuth.Unmarshal(m, b)
}
func (m *HTTPNoAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPNoAuth.Marshal(b, m, deterministic)
}
func (m *HTTPNoAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPNoAuth.Merge(m, src)
}
func (m *HTTPNoAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPNoAuth.Size(m)
}
func (m *HTTPNoAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPNoAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPNoAuth proto.InternalMessageInfo

func (m *HTTPNoAuth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HTTPNoAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HTTPNoAuth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *HTTPNoAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPNoAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPNoAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPNoAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPNoAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type HTTPAuth struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HealthcheckPath      string   `protobuf:"bytes,2,opt,name=healthcheck_path,json=healthcheckPath,proto3" json:"healthcheck_path,omitempty"`
	AuthHeader           string   `protobuf:"bytes,3,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	HeadersBlacklist     string   `protobuf:"bytes,4,opt,name=headers_blacklist,json=headersBlacklist,proto3" json:"headers_blacklist,omitempty"`
	DefaultPath          string   `protobuf:"bytes,5,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	Subdomain            string   `protobuf:"bytes,6,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPAuth) Reset()         { *m = HTTPAuth{} }
func (m *HTTPAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPAuth) ProtoMessage()    {}
func (*HTTPAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{10}
}

func (m *HTTPAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPAuth.Unmarshal(m, b)
}
func (m *HTTPAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPAuth.Marshal(b, m, deterministic)
}
func (m *HTTPAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPAuth.Merge(m, src)
}
func (m *HTTPAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPAuth.Size(m)
}
func (m *HTTPAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPAuth proto.InternalMessageInfo

func (m *HTTPAuth) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HTTPAuth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HTTPAuth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *HTTPAuth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HTTPAuth) GetHealthcheckPath() string {
	if m != nil {
		return m.HealthcheckPath
	}
	return ""
}

func (m *HTTPAuth) GetAuthHeader() string {
	if m != nil {
		return m.AuthHeader
	}
	return ""
}

func (m *HTTPAuth) GetHeadersBlacklist() string {
	if m != nil {
		return m.HeadersBlacklist
	}
	return ""
}

func (m *HTTPAuth) GetDefaultPath() string {
	if m != nil {
		return m.DefaultPath
	}
	return ""
}

func (m *HTTPAuth) GetSubdomain() string {
	if m != nil {
		return m.Subdomain
	}
	return ""
}

type Mysql struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	PortOverride         int32    `protobuf:"varint,5,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mysql) Reset()         { *m = Mysql{} }
func (m *Mysql) String() string { return proto.CompactTextString(m) }
func (*Mysql) ProtoMessage()    {}
func (*Mysql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{11}
}

func (m *Mysql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mysql.Unmarshal(m, b)
}
func (m *Mysql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mysql.Marshal(b, m, deterministic)
}
func (m *Mysql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mysql.Merge(m, src)
}
func (m *Mysql) XXX_Size() int {
	return xxx_messageInfo_Mysql.Size(m)
}
func (m *Mysql) XXX_DiscardUnknown() {
	xxx_messageInfo_Mysql.DiscardUnknown(m)
}

var xxx_messageInfo_Mysql proto.InternalMessageInfo

func (m *Mysql) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mysql) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mysql) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Mysql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Mysql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Mysql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Mysql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Mysql) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Mysql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type AuroraMysql struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	PortOverride         int32    `protobuf:"varint,5,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuroraMysql) Reset()         { *m = AuroraMysql{} }
func (m *AuroraMysql) String() string { return proto.CompactTextString(m) }
func (*AuroraMysql) ProtoMessage()    {}
func (*AuroraMysql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{12}
}

func (m *AuroraMysql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuroraMysql.Unmarshal(m, b)
}
func (m *AuroraMysql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuroraMysql.Marshal(b, m, deterministic)
}
func (m *AuroraMysql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuroraMysql.Merge(m, src)
}
func (m *AuroraMysql) XXX_Size() int {
	return xxx_messageInfo_AuroraMysql.Size(m)
}
func (m *AuroraMysql) XXX_DiscardUnknown() {
	xxx_messageInfo_AuroraMysql.DiscardUnknown(m)
}

var xxx_messageInfo_AuroraMysql proto.InternalMessageInfo

func (m *AuroraMysql) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuroraMysql) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuroraMysql) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *AuroraMysql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AuroraMysql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuroraMysql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuroraMysql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *AuroraMysql) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *AuroraMysql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Clustrix struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	PortOverride         int32    `protobuf:"varint,5,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clustrix) Reset()         { *m = Clustrix{} }
func (m *Clustrix) String() string { return proto.CompactTextString(m) }
func (*Clustrix) ProtoMessage()    {}
func (*Clustrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{13}
}

func (m *Clustrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clustrix.Unmarshal(m, b)
}
func (m *Clustrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clustrix.Marshal(b, m, deterministic)
}
func (m *Clustrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clustrix.Merge(m, src)
}
func (m *Clustrix) XXX_Size() int {
	return xxx_messageInfo_Clustrix.Size(m)
}
func (m *Clustrix) XXX_DiscardUnknown() {
	xxx_messageInfo_Clustrix.DiscardUnknown(m)
}

var xxx_messageInfo_Clustrix proto.InternalMessageInfo

func (m *Clustrix) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Clustrix) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Clustrix) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Clustrix) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Clustrix) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Clustrix) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Clustrix) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Clustrix) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Clustrix) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Maria struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	PortOverride         int32    `protobuf:"varint,5,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Maria) Reset()         { *m = Maria{} }
func (m *Maria) String() string { return proto.CompactTextString(m) }
func (*Maria) ProtoMessage()    {}
func (*Maria) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{14}
}

func (m *Maria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Maria.Unmarshal(m, b)
}
func (m *Maria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Maria.Marshal(b, m, deterministic)
}
func (m *Maria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Maria.Merge(m, src)
}
func (m *Maria) XXX_Size() int {
	return xxx_messageInfo_Maria.Size(m)
}
func (m *Maria) XXX_DiscardUnknown() {
	xxx_messageInfo_Maria.DiscardUnknown(m)
}

var xxx_messageInfo_Maria proto.InternalMessageInfo

func (m *Maria) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Maria) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Maria) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Maria) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Maria) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Maria) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Maria) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Maria) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Maria) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Memsql struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	PortOverride         int32    `protobuf:"varint,5,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memsql) Reset()         { *m = Memsql{} }
func (m *Memsql) String() string { return proto.CompactTextString(m) }
func (*Memsql) ProtoMessage()    {}
func (*Memsql) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{15}
}

func (m *Memsql) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memsql.Unmarshal(m, b)
}
func (m *Memsql) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memsql.Marshal(b, m, deterministic)
}
func (m *Memsql) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memsql.Merge(m, src)
}
func (m *Memsql) XXX_Size() int {
	return xxx_messageInfo_Memsql.Size(m)
}
func (m *Memsql) XXX_DiscardUnknown() {
	xxx_messageInfo_Memsql.DiscardUnknown(m)
}

var xxx_messageInfo_Memsql proto.InternalMessageInfo

func (m *Memsql) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Memsql) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Memsql) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Memsql) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Memsql) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Memsql) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Memsql) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Memsql) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Memsql) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Athena struct {
	// Unique identifier of the Resource.
	Id string `protobuf:"bytes,32768,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Resource.
	Name string `protobuf:"bytes,32769,opt,name=name,proto3" json:"name,omitempty"`
	// True if the datasource is reachable and the credentials are valid.
	Healthy              bool     `protobuf:"varint,32770,opt,name=healthy,proto3" json:"healthy,omitempty"`
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Output               string   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	PortOverride         int32    `protobuf:"varint,4,opt,name=port_override,json=portOverride,proto3" json:"port_override,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Athena) Reset()         { *m = Athena{} }
func (m *Athena) String() string { return proto.CompactTextString(m) }
func (*Athena) ProtoMessage()    {}
func (*Athena) Descriptor() ([]byte, []int) {
	return fileDescriptor_81dfd49b5b303fb4, []int{16}
}

func (m *Athena) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Athena.Unmarshal(m, b)
}
func (m *Athena) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Athena.Marshal(b, m, deterministic)
}
func (m *Athena) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Athena.Merge(m, src)
}
func (m *Athena) XXX_Size() int {
	return xxx_messageInfo_Athena.Size(m)
}
func (m *Athena) XXX_DiscardUnknown() {
	xxx_messageInfo_Athena.DiscardUnknown(m)
}

var xxx_messageInfo_Athena proto.InternalMessageInfo

func (m *Athena) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Athena) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Athena) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *Athena) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *Athena) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *Athena) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Athena) GetPortOverride() int32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

func (m *Athena) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func init() {
	proto.RegisterType((*Resource)(nil), "v1.Resource")
	proto.RegisterType((*Redis)(nil), "v1.Redis")
	proto.RegisterType((*ElasticacheRedis)(nil), "v1.ElasticacheRedis")
	proto.RegisterType((*Kubernetes)(nil), "v1.Kubernetes")
	proto.RegisterType((*KubernetesBasicAuth)(nil), "v1.KubernetesBasicAuth")
	proto.RegisterType((*AmazonEKS)(nil), "v1.AmazonEKS")
	proto.RegisterType((*GoogleGKE)(nil), "v1.GoogleGKE")
	proto.RegisterType((*SSH)(nil), "v1.SSH")
	proto.RegisterType((*HTTPBasicAuth)(nil), "v1.HTTPBasicAuth")
	proto.RegisterType((*HTTPNoAuth)(nil), "v1.HTTPNoAuth")
	proto.RegisterType((*HTTPAuth)(nil), "v1.HTTPAuth")
	proto.RegisterType((*Mysql)(nil), "v1.Mysql")
	proto.RegisterType((*AuroraMysql)(nil), "v1.AuroraMysql")
	proto.RegisterType((*Clustrix)(nil), "v1.Clustrix")
	proto.RegisterType((*Maria)(nil), "v1.Maria")
	proto.RegisterType((*Memsql)(nil), "v1.Memsql")
	proto.RegisterType((*Athena)(nil), "v1.Athena")
}

func init() { proto.RegisterFile("drivers.proto", fileDescriptor_81dfd49b5b303fb4) }

var fileDescriptor_81dfd49b5b303fb4 = []byte{
	// 1435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x4d, 0x6c, 0x1b, 0x45,
	0x18, 0x8d, 0xd7, 0x3f, 0xb1, 0x3f, 0xc7, 0x24, 0xde, 0xb4, 0x62, 0x55, 0x55, 0xa8, 0x8a, 0x68,
	0xda, 0xaa, 0xc4, 0x69, 0x9a, 0x92, 0xaa, 0xb9, 0x14, 0xbb, 0x84, 0x5a, 0x8a, 0x28, 0xc5, 0xe9,
	0x7d, 0x35, 0x5e, 0x4f, 0xed, 0x95, 0xd7, 0xbb, 0xee, 0xcc, 0x6c, 0x4a, 0x7a, 0x4a, 0x7b, 0x40,
	0x1c, 0xb8, 0x10, 0x85, 0x13, 0x70, 0x00, 0x54, 0x44, 0x2b, 0x51, 0x90, 0xda, 0x03, 0x5c, 0x01,
	0x89, 0x23, 0x42, 0xa8, 0xe2, 0x42, 0x01, 0x09, 0x71, 0x42, 0x2d, 0x7f, 0x12, 0x42, 0x85, 0x02,
	0x9a, 0x99, 0xb5, 0x77, 0x9d, 0xdd, 0xb6, 0x49, 0x41, 0x56, 0x5b, 0xe5, 0xe6, 0x9d, 0xf7, 0xde,
	0x97, 0x99, 0xf7, 0x66, 0x66, 0x77, 0x26, 0x90, 0xab, 0x11, 0x73, 0x11, 0x13, 0x5a, 0x68, 0x13,
	0x87, 0x39, 0xaa, 0xb2, 0x38, 0xb5, 0xed, 0x09, 0xf1, 0xd3, 0x98, 0xa8, 0x63, 0x7b, 0x82, 0x9e,
	0x46, 0xf5, 0x3a, 0x26, 0x93, 0x4e, 0x9b, 0x99, 0x8e, 0x4d, 0x27, 0x91, 0x6d, 0x3b, 0x0c, 0x89,
	0xdf, 0x52, 0xb1, 0x2d, 0xe7, 0x41, 0xf2, 0x71, 0xec, 0x8b, 0x14, 0xa4, 0x2b, 0x98, 0x3a, 0x2e,
	0x31, 0xb0, 0xfa, 0x38, 0x24, 0x09, 0xae, 0x99, 0x54, 0xbb, 0xf2, 0xfb, 0x6b, 0xa5, 0x1d, 0xb1,
	0xdd, 0xd9, 0xfd, 0x99, 0xc2, 0xe2, 0x54, 0xa1, 0xc2, 0xdb, 0xca, 0x03, 0x15, 0x09, 0xaa, 0xcf,
	0x40, 0x1e, 0x5b, 0x88, 0x32, 0xd3, 0x40, 0x46, 0x03, 0xeb, 0x52, 0xf1, 0xd9, 0xb5, 0xf7, 0x73,
	0x42, 0xb1, 0x85, 0x2b, 0xe6, 0x7c, 0xbc, 0x23, 0x1e, 0xc1, 0x6b, 0xda, 0xd4, 0x69, 0x80, 0xa6,
	0x5b, 0xc5, 0xc4, 0xc6, 0x0c, 0x53, 0x6d, 0xf5, 0xab, 0x4b, 0xb6, 0x28, 0xf0, 0x08, 0x2f, 0x30,
	0xdf, 0x05, 0xca, 0x03, 0x95, 0x00, 0x4d, 0x7d, 0x1e, 0xb6, 0xfa, 0x4f, 0x7a, 0x15, 0x51, 0xd3,
	0xd0, 0x91, 0xcb, 0x1a, 0xda, 0x4f, 0x5f, 0xfe, 0xfd, 0x5d, 0x4c, 0x14, 0x78, 0xb4, 0xb7, 0x40,
	0x89, 0x73, 0x8a, 0x2e, 0x6b, 0x94, 0x07, 0x2a, 0xa3, 0xcd, 0x70, 0xb3, 0x3a, 0x05, 0x80, 0x5a,
	0xe8, 0x8c, 0x63, 0xeb, 0xb8, 0x49, 0xb5, 0x9f, 0xcf, 0x9f, 0x9d, 0x13, 0x65, 0x72, 0xbc, 0x4c,
	0x51, 0x00, 0x73, 0xf3, 0x0b, 0xe5, 0x81, 0x4a, 0x46, 0xb2, 0xe6, 0x9a, 0x94, 0x4b, 0xea, 0x8e,
	0x53, 0xb7, 0xb0, 0x5e, 0x6f, 0x62, 0xed, 0xd5, 0x4b, 0xaf, 0x94, 0x7c, 0xc9, 0x51, 0x01, 0x1c,
	0x9d, 0x9f, 0xe3, 0x12, 0xc9, 0x3a, 0xda, 0xc4, 0xea, 0x63, 0x10, 0xa7, 0xb4, 0xa1, 0xfd, 0x73,
	0xe5, 0xea, 0x19, 0xc1, 0x1d, 0xe4, 0xdc, 0x85, 0x85, 0x72, 0x79, 0xa0, 0xc2, 0x01, 0xf5, 0x30,
	0x0c, 0x37, 0x18, 0x6b, 0x07, 0x87, 0xf4, 0xf2, 0xc5, 0xef, 0xaf, 0xca, 0x21, 0xe5, 0x39, 0xb9,
	0x7c, 0xe2, 0xc4, 0xf1, 0xe0, 0x60, 0x72, 0x9c, 0xef, 0x0f, 0x63, 0x06, 0x86, 0x44, 0x01, 0xdb,
	0x91, 0xea, 0x37, 0x2e, 0xfe, 0xf0, 0x79, 0xcc, 0x77, 0x94, 0xab, 0x8f, 0x39, 0x9e, 0x14, 0x38,
	0x53, 0x3e, 0xa9, 0x05, 0xc8, 0x08, 0x9d, 0x10, 0xdd, 0xf8, 0xf8, 0x5c, 0x53, 0x68, 0x86, 0x3a,
	0x1a, 0x4f, 0x91, 0xe6, 0x1c, 0xc1, 0xdf, 0x09, 0xc9, 0xd6, 0x12, 0x3d, 0x65, 0x69, 0x9f, 0x2c,
	0xaf, 0x7e, 0x18, 0xf3, 0x67, 0xc9, 0xb3, 0xbc, 0x91, 0xcf, 0x12, 0x81, 0xaa, 0x07, 0x61, 0x08,
	0xb9, 0xc4, 0x21, 0x48, 0x97, 0xec, 0xeb, 0x6f, 0x7d, 0x9d, 0x16, 0xe4, 0x61, 0xe1, 0xab, 0x80,
	0x3a, 0x92, 0x2c, 0xf2, 0x1f, 0xd5, 0x02, 0xa4, 0x0d, 0xcb, 0xa5, 0x8c, 0x98, 0x2f, 0x68, 0xab,
	0x17, 0x6e, 0xdc, 0x8a, 0xf9, 0xfd, 0x39, 0xe2, 0xb5, 0xf3, 0xfe, 0x74, 0x38, 0xa2, 0x3f, 0x88,
	0x98, 0x48, 0x5b, 0xbd, 0xf6, 0xce, 0x37, 0xc1, 0xfe, 0xf0, 0x46, 0xd1, 0x1f, 0xfe, 0x43, 0xdd,
	0x0d, 0xa9, 0x16, 0x6e, 0xf1, 0x9e, 0xbc, 0xf7, 0xd1, 0xb7, 0xcb, 0x92, 0x07, 0x82, 0x27, 0x5a,
	0xcb, 0x03, 0x15, 0x0f, 0x57, 0x77, 0x41, 0x0a, 0xb1, 0x06, 0xb6, 0x91, 0xf6, 0xd2, 0x8b, 0x6f,
	0xee, 0xf1, 0x89, 0x45, 0xd1, 0xc8, 0x89, 0x12, 0x9e, 0x85, 0x9b, 0x7f, 0x5c, 0x1e, 0x4c, 0xbe,
	0xfb, 0xdb, 0xe5, 0xc1, 0x58, 0x09, 0x20, 0x4d, 0xbc, 0x65, 0x34, 0x76, 0x51, 0x81, 0xa4, 0x9c,
	0xe2, 0xdb, 0x41, 0x31, 0x6b, 0xda, 0xf2, 0xb2, 0xb2, 0x23, 0xb6, 0x3b, 0x53, 0x82, 0x5f, 0x39,
	0xff, 0x03, 0xce, 0xaf, 0x28, 0x66, 0x4d, 0xdd, 0x01, 0x09, 0x1b, 0xb5, 0xb0, 0x76, 0x36, 0x02,
	0x17, 0x88, 0xba, 0x17, 0x06, 0x1b, 0x18, 0x59, 0xac, 0xb1, 0xa4, 0x9d, 0x13, 0xa4, 0x74, 0x69,
	0x78, 0xa5, 0xa8, 0x3c, 0x15, 0x0b, 0x30, 0x3b, 0x0c, 0x75, 0x1c, 0xd2, 0x0d, 0x87, 0x32, 0x51,
	0x32, 0x16, 0x2a, 0xd8, 0xc5, 0xd4, 0x49, 0xc8, 0xb5, 0x1d, 0xc2, 0x74, 0x67, 0x11, 0x13, 0x62,
	0xd6, 0xb0, 0xc6, 0x0b, 0x27, 0x7b, 0xc8, 0x43, 0x9c, 0xf0, 0x9c, 0x87, 0xf3, 0xc2, 0x6d, 0x44,
	0xe9, 0x69, 0x87, 0xd4, 0xb4, 0x78, 0xb8, 0x70, 0x07, 0x53, 0x77, 0x41, 0x82, 0xeb, 0xb4, 0x84,
	0xa8, 0x37, 0xba, 0x52, 0x4c, 0xcd, 0x26, 0x66, 0xa6, 0x0f, 0x1e, 0x0a, 0x0e, 0x8b, 0x13, 0x82,
	0xc6, 0x8d, 0x5d, 0x57, 0x60, 0x64, 0xed, 0x76, 0xb1, 0xe9, 0x5b, 0xa4, 0x6f, 0x7c, 0x89, 0x33,
	0x8b, 0xea, 0x04, 0x9f, 0x72, 0x4d, 0x82, 0x6b, 0x5a, 0x52, 0x8c, 0x4c, 0x0a, 0x18, 0x71, 0x71,
	0x40, 0x90, 0x65, 0x16, 0xad, 0x78, 0xbc, 0x1e, 0xbf, 0xff, 0x52, 0x00, 0xfc, 0xcd, 0xf1, 0xfe,
	0x74, 0x7a, 0xdc, 0x33, 0x44, 0x1a, 0xac, 0xae, 0x14, 0x93, 0xb3, 0xf1, 0x03, 0x07, 0xa6, 0x43,
	0x7e, 0x1c, 0x86, 0xad, 0x06, 0x26, 0xcc, 0x3c, 0x69, 0x1a, 0x88, 0x61, 0xb1, 0x83, 0x39, 0xc4,
	0x64, 0x4b, 0x11, 0x6e, 0x6f, 0x09, 0x10, 0x8b, 0x1d, 0x9e, 0x7a, 0x08, 0x54, 0xc3, 0x32, 0xb1,
	0xcd, 0xf4, 0x00, 0x2c, 0x72, 0xe8, 0x55, 0xe7, 0x25, 0xeb, 0x88, 0x4f, 0x52, 0xf7, 0x00, 0x78,
	0xd2, 0x26, 0x5e, 0x12, 0x49, 0xf4, 0x4a, 0x32, 0x12, 0x9d, 0xc7, 0x4b, 0x3d, 0xf6, 0x5f, 0x8d,
	0xc3, 0x68, 0xc4, 0xbb, 0xe9, 0xc1, 0xce, 0x61, 0x1c, 0xd2, 0x2e, 0xc5, 0x44, 0xd4, 0x8b, 0x98,
	0xe8, 0x1d, 0xac, 0x67, 0x41, 0x24, 0xee, 0xb0, 0x20, 0x6e, 0x9b, 0x6b, 0xf2, 0x3f, 0xe5, 0x9a,
	0xda, 0x78, 0xae, 0x83, 0xeb, 0xcd, 0xf5, 0xed, 0x38, 0x64, 0xba, 0x1f, 0x0b, 0x7d, 0x4f, 0x13,
	0xdb, 0xb5, 0xb6, 0x63, 0xda, 0x2c, 0x2a, 0xcd, 0x0e, 0xc6, 0x47, 0x86, 0x0c, 0x03, 0x53, 0x2a,
	0x46, 0x16, 0xfe, 0xd3, 0x19, 0x89, 0xce, 0xe3, 0x25, 0x75, 0x06, 0xf2, 0x14, 0x1b, 0x04, 0x33,
	0x3d, 0xa0, 0x08, 0x27, 0x3b, 0x2c, 0x49, 0xc5, 0xae, 0xee, 0xb6, 0xc1, 0x25, 0xd6, 0x19, 0xdc,
	0x18, 0xa4, 0x08, 0xae, 0x9b, 0x8e, 0x1d, 0x11, 0xb5, 0x87, 0xa8, 0x13, 0x30, 0x24, 0x5e, 0xfe,
	0x98, 0xe8, 0xc2, 0xc6, 0x70, 0xac, 0x59, 0x0f, 0x3f, 0x86, 0x5a, 0xb8, 0x27, 0xa5, 0x0b, 0x0a,
	0x64, 0xba, 0xdf, 0x67, 0xf7, 0x67, 0x4a, 0xb7, 0xb5, 0x50, 0x59, 0xa7, 0x85, 0xb3, 0x30, 0x4a,
	0x31, 0x59, 0x34, 0x0d, 0xcc, 0xc3, 0x73, 0x5c, 0x6f, 0x26, 0x87, 0xd3, 0xcb, 0x7b, 0xb4, 0xa2,
	0x64, 0xad, 0x9d, 0xd1, 0xe7, 0x15, 0x88, 0x2f, 0x2c, 0x94, 0xef, 0xd7, 0x9d, 0xc9, 0xdf, 0x71,
	0x94, 0x3b, 0xec, 0x38, 0x3b, 0xbd, 0x1d, 0x2c, 0x2e, 0x76, 0xb0, 0xfc, 0x4a, 0x31, 0x31, 0xab,
	0xec, 0xdf, 0x1f, 0xda, 0xc0, 0x0a, 0x00, 0x6d, 0xb7, 0x6a, 0x99, 0x86, 0xb0, 0x4a, 0x4e, 0xd6,
	0x50, 0x27, 0x33, 0x92, 0xb2, 0xd6, 0xa7, 0x4f, 0xe3, 0x90, 0xeb, 0xf9, 0x34, 0xef, 0xaf, 0x63,
	0xdb, 0x21, 0xee, 0x12, 0x2b, 0xc2, 0x2c, 0xde, 0xac, 0x3e, 0x09, 0x23, 0x92, 0x68, 0x34, 0xb0,
	0xd1, 0xd4, 0xdb, 0x88, 0x35, 0x22, 0xfc, 0x1a, 0x0e, 0x70, 0x8e, 0x23, 0xd6, 0xf8, 0xdf, 0x37,
	0xf4, 0x83, 0x90, 0x6f, 0x60, 0x54, 0xc3, 0x84, 0xea, 0x55, 0x0b, 0x19, 0x4d, 0xcb, 0xa4, 0x2c,
	0x62, 0x85, 0x8f, 0x78, 0xa4, 0x52, 0x87, 0xc3, 0xd7, 0x7a, 0x0d, 0x9f, 0x44, 0xae, 0xc5, 0x64,
	0xdf, 0x23, 0xd6, 0xba, 0x87, 0x8b, 0x7e, 0x4f, 0x40, 0x86, 0xba, 0xd5, 0x9a, 0xd3, 0x42, 0xa6,
	0xed, 0xed, 0xdd, 0xe1, 0x18, 0xbb, 0x8c, 0x9e, 0x18, 0x7f, 0x51, 0x00, 0xfc, 0x33, 0xd2, 0x43,
	0x90, 0x61, 0xa4, 0xe7, 0xf1, 0x7b, 0xf0, 0x3c, 0xb1, 0x01, 0xcf, 0x93, 0x1b, 0xf2, 0xfc, 0xf5,
	0x38, 0xa4, 0x3b, 0x67, 0xcc, 0x87, 0xc0, 0xf1, 0xbd, 0x90, 0xe5, 0xdb, 0xb5, 0x2e, 0x1d, 0x8d,
	0xf0, 0x1a, 0x38, 0x5c, 0x16, 0x68, 0x74, 0x3c, 0x89, 0x7b, 0x88, 0x27, 0xb9, 0x81, 0x78, 0x52,
	0x1b, 0x8a, 0xe7, 0xa6, 0x02, 0x49, 0x79, 0x26, 0x7f, 0xa0, 0xdf, 0x01, 0xeb, 0x3d, 0x86, 0x8d,
	0x43, 0xba, 0x86, 0x18, 0xaa, 0x22, 0x1a, 0x75, 0x04, 0xe8, 0x62, 0xe1, 0x73, 0x60, 0xf2, 0x2e,
	0xe7, 0xc0, 0xce, 0xf9, 0x2e, 0x15, 0x38, 0xdf, 0x4d, 0x4f, 0xef, 0x9b, 0xb9, 0xe3, 0xb9, 0x78,
	0x39, 0x0e, 0xd9, 0xc0, 0x2d, 0xc9, 0x66, 0x04, 0xfd, 0x8f, 0xe0, 0x96, 0x02, 0xe9, 0xce, 0x95,
	0xd3, 0xa6, 0xff, 0xfd, 0xf7, 0x5f, 0xec, 0x3f, 0xe2, 0xf2, 0x6e, 0xd3, 0xfc, 0xbe, 0x9b, 0xff,
	0xa7, 0x02, 0x29, 0x79, 0x35, 0xba, 0xe9, 0x7e, 0xff, 0xdd, 0xff, 0x51, 0x81, 0x94, 0xbc, 0x6f,
	0xee, 0xaf, 0xfb, 0xbd, 0x77, 0x04, 0xb1, 0x0d, 0xdf, 0x11, 0x28, 0x77, 0xbf, 0x23, 0x18, 0x83,
	0x94, 0xe3, 0xb2, 0xb6, 0x1b, 0xf5, 0x31, 0xea, 0x21, 0x61, 0x93, 0x13, 0x77, 0x31, 0x79, 0xdf,
	0x9a, 0x7b, 0x03, 0x6d, 0xa5, 0x98, 0x9d, 0xcd, 0xb8, 0x74, 0x02, 0x23, 0xca, 0x26, 0xa6, 0xc2,
	0xb7, 0x08, 0x3d, 0x97, 0xf7, 0x93, 0xb0, 0xdd, 0x70, 0x5a, 0x05, 0xca, 0x88, 0x63, 0xd7, 0x6b,
	0xad, 0x02, 0x6a, 0x9b, 0x85, 0xc5, 0xa9, 0x42, 0xdb, 0x72, 0x5b, 0x55, 0xd3, 0xae, 0x97, 0x86,
	0x9f, 0x96, 0xff, 0x74, 0x3b, 0xee, 0x35, 0x54, 0x53, 0xe2, 0x9f, 0x67, 0xd3, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0x7a, 0x12, 0x09, 0x8e, 0x1b, 0x00, 0x00,
}
