// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodes.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NodeCreateRequest specifies what kind of Node should be registered in the
// organizations fleet. Note that a Node must be either a Relay or a Gateway.
type NodeCreateRequest struct {
	// Reserved for future use.
	Meta *CreateRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Parameters to define the new Node.
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCreateRequest) Reset()         { *m = NodeCreateRequest{} }
func (m *NodeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*NodeCreateRequest) ProtoMessage()    {}
func (*NodeCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{0}
}

func (m *NodeCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCreateRequest.Unmarshal(m, b)
}
func (m *NodeCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCreateRequest.Marshal(b, m, deterministic)
}
func (m *NodeCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCreateRequest.Merge(m, src)
}
func (m *NodeCreateRequest) XXX_Size() int {
	return xxx_messageInfo_NodeCreateRequest.Size(m)
}
func (m *NodeCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCreateRequest proto.InternalMessageInfo

func (m *NodeCreateRequest) GetMeta() *CreateRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeCreateRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// NodeCreateResponse reports how the Nodes were created in the system.
type NodeCreateResponse struct {
	// Reserved for future use.
	Meta *CreateResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The created Node.
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// The auth token generated for the Node. The Node will use this token to
	// authenticate with the strongDM API.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Rate limit information.
	RateLimit            *RateLimitMetadata `protobuf:"bytes,4,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeCreateResponse) Reset()         { *m = NodeCreateResponse{} }
func (m *NodeCreateResponse) String() string { return proto.CompactTextString(m) }
func (*NodeCreateResponse) ProtoMessage()    {}
func (*NodeCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{1}
}

func (m *NodeCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCreateResponse.Unmarshal(m, b)
}
func (m *NodeCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCreateResponse.Marshal(b, m, deterministic)
}
func (m *NodeCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCreateResponse.Merge(m, src)
}
func (m *NodeCreateResponse) XXX_Size() int {
	return xxx_messageInfo_NodeCreateResponse.Size(m)
}
func (m *NodeCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCreateResponse proto.InternalMessageInfo

func (m *NodeCreateResponse) GetMeta() *CreateResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeCreateResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeCreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *NodeCreateResponse) GetRateLimit() *RateLimitMetadata {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

// NodeGetRequest specifies which Node to retrieve.
type NodeGetRequest struct {
	// Reserved for future use.
	Meta *GetRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The unique identifier of the Node to retrieve.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGetRequest) Reset()         { *m = NodeGetRequest{} }
func (m *NodeGetRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGetRequest) ProtoMessage()    {}
func (*NodeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{2}
}

func (m *NodeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGetRequest.Unmarshal(m, b)
}
func (m *NodeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGetRequest.Marshal(b, m, deterministic)
}
func (m *NodeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGetRequest.Merge(m, src)
}
func (m *NodeGetRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGetRequest.Size(m)
}
func (m *NodeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGetRequest proto.InternalMessageInfo

func (m *NodeGetRequest) GetMeta() *GetRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// NodeGetResponse returns a requested Node.
type NodeGetResponse struct {
	// Reserved for future use.
	Meta *GetResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The requested Node.
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Rate limit information.
	RateLimit            *RateLimitMetadata `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeGetResponse) Reset()         { *m = NodeGetResponse{} }
func (m *NodeGetResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGetResponse) ProtoMessage()    {}
func (*NodeGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{3}
}

func (m *NodeGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGetResponse.Unmarshal(m, b)
}
func (m *NodeGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGetResponse.Marshal(b, m, deterministic)
}
func (m *NodeGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGetResponse.Merge(m, src)
}
func (m *NodeGetResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGetResponse.Size(m)
}
func (m *NodeGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGetResponse proto.InternalMessageInfo

func (m *NodeGetResponse) GetMeta() *GetResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeGetResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeGetResponse) GetRateLimit() *RateLimitMetadata {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

// NodeUpdateRequest identifies a Node by ID and provides fields to update on
// that Node record.
type NodeUpdateRequest struct {
	// Reserved for future use.
	Meta *UpdateRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The unique identifier of the Node to update. If an ID is already
	// specified in the `node` field, this field is not required. If an ID is
	// specified in both places, they must match.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Parameters to overwrite the specified Node.
	Node                 *Node    `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeUpdateRequest) Reset()         { *m = NodeUpdateRequest{} }
func (m *NodeUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*NodeUpdateRequest) ProtoMessage()    {}
func (*NodeUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{4}
}

func (m *NodeUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeUpdateRequest.Unmarshal(m, b)
}
func (m *NodeUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeUpdateRequest.Marshal(b, m, deterministic)
}
func (m *NodeUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeUpdateRequest.Merge(m, src)
}
func (m *NodeUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_NodeUpdateRequest.Size(m)
}
func (m *NodeUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeUpdateRequest proto.InternalMessageInfo

func (m *NodeUpdateRequest) GetMeta() *UpdateRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeUpdateRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// NodeUpdateResponse returns the fields of a Node after it has been updated by
// a NodeUpdateRequest.
type NodeUpdateResponse struct {
	// Reserved for future use.
	Meta *UpdateResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The updated Node.
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Rate limit information.
	RateLimit            *RateLimitMetadata `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeUpdateResponse) Reset()         { *m = NodeUpdateResponse{} }
func (m *NodeUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*NodeUpdateResponse) ProtoMessage()    {}
func (*NodeUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{5}
}

func (m *NodeUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeUpdateResponse.Unmarshal(m, b)
}
func (m *NodeUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeUpdateResponse.Marshal(b, m, deterministic)
}
func (m *NodeUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeUpdateResponse.Merge(m, src)
}
func (m *NodeUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_NodeUpdateResponse.Size(m)
}
func (m *NodeUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeUpdateResponse proto.InternalMessageInfo

func (m *NodeUpdateResponse) GetMeta() *UpdateResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeUpdateResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NodeUpdateResponse) GetRateLimit() *RateLimitMetadata {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

// NodeDeleteRequest identifies a Node by ID to delete.
type NodeDeleteRequest struct {
	// Reserved for future use.
	Meta *DeleteRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The unique identifier of the Node to delete.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDeleteRequest) Reset()         { *m = NodeDeleteRequest{} }
func (m *NodeDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*NodeDeleteRequest) ProtoMessage()    {}
func (*NodeDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{6}
}

func (m *NodeDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDeleteRequest.Unmarshal(m, b)
}
func (m *NodeDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDeleteRequest.Marshal(b, m, deterministic)
}
func (m *NodeDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDeleteRequest.Merge(m, src)
}
func (m *NodeDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_NodeDeleteRequest.Size(m)
}
func (m *NodeDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDeleteRequest proto.InternalMessageInfo

func (m *NodeDeleteRequest) GetMeta() *DeleteRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// NodeDeleteResponse returns information about a Node that was deleted.
type NodeDeleteResponse struct {
	// Reserved for future use.
	Meta *DeleteResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Rate limit information.
	RateLimit            *RateLimitMetadata `protobuf:"bytes,2,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeDeleteResponse) Reset()         { *m = NodeDeleteResponse{} }
func (m *NodeDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*NodeDeleteResponse) ProtoMessage()    {}
func (*NodeDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{7}
}

func (m *NodeDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDeleteResponse.Unmarshal(m, b)
}
func (m *NodeDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDeleteResponse.Marshal(b, m, deterministic)
}
func (m *NodeDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDeleteResponse.Merge(m, src)
}
func (m *NodeDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_NodeDeleteResponse.Size(m)
}
func (m *NodeDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDeleteResponse proto.InternalMessageInfo

func (m *NodeDeleteResponse) GetMeta() *DeleteResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeDeleteResponse) GetRateLimit() *RateLimitMetadata {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

// NodeListRequest specifies criteria for retrieving a list of Nodes.
type NodeListRequest struct {
	// Paging parameters for the query.
	Meta *ListRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// A human-readable filter query string.
	Filter               string   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeListRequest) Reset()         { *m = NodeListRequest{} }
func (m *NodeListRequest) String() string { return proto.CompactTextString(m) }
func (*NodeListRequest) ProtoMessage()    {}
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{8}
}

func (m *NodeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListRequest.Unmarshal(m, b)
}
func (m *NodeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListRequest.Marshal(b, m, deterministic)
}
func (m *NodeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListRequest.Merge(m, src)
}
func (m *NodeListRequest) XXX_Size() int {
	return xxx_messageInfo_NodeListRequest.Size(m)
}
func (m *NodeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListRequest proto.InternalMessageInfo

func (m *NodeListRequest) GetMeta() *ListRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// NodeListResponse returns a list of Nodes that meet the criteria of a
// NodeListRequest.
type NodeListResponse struct {
	// Paging information for the query.
	Meta *ListResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// A single page of results matching the list request criteria.
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Rate limit information.
	RateLimit            *RateLimitMetadata `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeListResponse) Reset()         { *m = NodeListResponse{} }
func (m *NodeListResponse) String() string { return proto.CompactTextString(m) }
func (*NodeListResponse) ProtoMessage()    {}
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{9}
}

func (m *NodeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeListResponse.Unmarshal(m, b)
}
func (m *NodeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeListResponse.Marshal(b, m, deterministic)
}
func (m *NodeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeListResponse.Merge(m, src)
}
func (m *NodeListResponse) XXX_Size() int {
	return xxx_messageInfo_NodeListResponse.Size(m)
}
func (m *NodeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeListResponse proto.InternalMessageInfo

func (m *NodeListResponse) GetMeta() *ListResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *NodeListResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *NodeListResponse) GetRateLimit() *RateLimitMetadata {
	if m != nil {
		return m.RateLimit
	}
	return nil
}

// A Node is a proxy in the strongDM network. They come in two flavors: relays,
// which communicate with resources, and gateways, which communicate with
// clients.
type Node struct {
	// Types that are valid to be assigned to Node:
	//	*Node_Relay
	//	*Node_Gateway
	Node                 isNode_Node `protobuf_oneof:"node"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{10}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type isNode_Node interface {
	isNode_Node()
}

type Node_Relay struct {
	Relay *Relay `protobuf:"bytes,1,opt,name=relay,proto3,oneof"`
}

type Node_Gateway struct {
	Gateway *Gateway `protobuf:"bytes,2,opt,name=gateway,proto3,oneof"`
}

func (*Node_Relay) isNode_Node() {}

func (*Node_Gateway) isNode_Node() {}

func (m *Node) GetNode() isNode_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *Node) GetRelay() *Relay {
	if x, ok := m.GetNode().(*Node_Relay); ok {
		return x.Relay
	}
	return nil
}

func (m *Node) GetGateway() *Gateway {
	if x, ok := m.GetNode().(*Node_Gateway); ok {
		return x.Gateway
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Node) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Node_Relay)(nil),
		(*Node_Gateway)(nil),
	}
}

// Relay represents a StrongDM CLI installation running in relay mode.
type Relay struct {
	// Unique identifier of the Relay.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Relay.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The current state of the relay. One of: "new", "verifying_restart",
	// "restarting", "started", "stopped", "dead", "unknown",
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Relay) Reset()         { *m = Relay{} }
func (m *Relay) String() string { return proto.CompactTextString(m) }
func (*Relay) ProtoMessage()    {}
func (*Relay) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{11}
}

func (m *Relay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relay.Unmarshal(m, b)
}
func (m *Relay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relay.Marshal(b, m, deterministic)
}
func (m *Relay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relay.Merge(m, src)
}
func (m *Relay) XXX_Size() int {
	return xxx_messageInfo_Relay.Size(m)
}
func (m *Relay) XXX_DiscardUnknown() {
	xxx_messageInfo_Relay.DiscardUnknown(m)
}

var xxx_messageInfo_Relay proto.InternalMessageInfo

func (m *Relay) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Relay) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Relay) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// Gateway represents a StrongDM CLI installation running in gateway mode.
type Gateway struct {
	// Unique identifier of the Relay.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name of the Relay.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The current state of the gateway. One of: "new", "verifying_restart",
	// "restarting", "started", "stopped", "dead", "unknown",
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// The public hostname/port tuple at which the gateway will be accessible to clients.
	ListenAddress string `protobuf:"bytes,4,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	// The hostname/port tuple which the gateway daemon will bind to.
	BindAddress          string   `protobuf:"bytes,5,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gateway) Reset()         { *m = Gateway{} }
func (m *Gateway) String() string { return proto.CompactTextString(m) }
func (*Gateway) ProtoMessage()    {}
func (*Gateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b18f0c01aa3995, []int{12}
}

func (m *Gateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gateway.Unmarshal(m, b)
}
func (m *Gateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gateway.Marshal(b, m, deterministic)
}
func (m *Gateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gateway.Merge(m, src)
}
func (m *Gateway) XXX_Size() int {
	return xxx_messageInfo_Gateway.Size(m)
}
func (m *Gateway) XXX_DiscardUnknown() {
	xxx_messageInfo_Gateway.DiscardUnknown(m)
}

var xxx_messageInfo_Gateway proto.InternalMessageInfo

func (m *Gateway) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gateway) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Gateway) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Gateway) GetListenAddress() string {
	if m != nil {
		return m.ListenAddress
	}
	return ""
}

func (m *Gateway) GetBindAddress() string {
	if m != nil {
		return m.BindAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeCreateRequest)(nil), "v1.NodeCreateRequest")
	proto.RegisterType((*NodeCreateResponse)(nil), "v1.NodeCreateResponse")
	proto.RegisterType((*NodeGetRequest)(nil), "v1.NodeGetRequest")
	proto.RegisterType((*NodeGetResponse)(nil), "v1.NodeGetResponse")
	proto.RegisterType((*NodeUpdateRequest)(nil), "v1.NodeUpdateRequest")
	proto.RegisterType((*NodeUpdateResponse)(nil), "v1.NodeUpdateResponse")
	proto.RegisterType((*NodeDeleteRequest)(nil), "v1.NodeDeleteRequest")
	proto.RegisterType((*NodeDeleteResponse)(nil), "v1.NodeDeleteResponse")
	proto.RegisterType((*NodeListRequest)(nil), "v1.NodeListRequest")
	proto.RegisterType((*NodeListResponse)(nil), "v1.NodeListResponse")
	proto.RegisterType((*Node)(nil), "v1.Node")
	proto.RegisterType((*Relay)(nil), "v1.Relay")
	proto.RegisterType((*Gateway)(nil), "v1.Gateway")
}

func init() { proto.RegisterFile("nodes.proto", fileDescriptor_39b18f0c01aa3995) }

var fileDescriptor_39b18f0c01aa3995 = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xee, 0xae, 0xed, 0xb8, 0x1e, 0xb7, 0x6e, 0x33, 0xa1, 0xa9, 0x63, 0x45, 0x68, 0x3b, 0x45,
	0x6a, 0x64, 0x62, 0xaf, 0x12, 0x90, 0x22, 0xf9, 0x02, 0x36, 0x81, 0x16, 0x29, 0x04, 0xe4, 0xaa,
	0x12, 0x27, 0xaa, 0xb1, 0xf7, 0xe1, 0xac, 0xba, 0xbb, 0xb3, 0xec, 0x4c, 0x63, 0x45, 0xa5, 0x17,
	0x7e, 0x42, 0x38, 0x71, 0x0d, 0x42, 0x42, 0x9c, 0x90, 0x2c, 0x21, 0x0e, 0x9c, 0x38, 0x72, 0xe5,
	0x88, 0xc4, 0x89, 0x5f, 0xd0, 0x5e, 0xd2, 0x9e, 0xd0, 0xcc, 0xce, 0xee, 0x66, 0x4c, 0x9a, 0xaa,
	0x11, 0x12, 0x9c, 0x92, 0x9d, 0xf7, 0xcd, 0xf7, 0xde, 0xfb, 0xe6, 0x9b, 0x37, 0x46, 0xf5, 0x88,
	0x79, 0xc0, 0xbb, 0x71, 0xc2, 0x04, 0xc3, 0xf6, 0xfe, 0x46, 0x6b, 0x75, 0xc2, 0xd8, 0x24, 0x00,
	0x97, 0xc6, 0xbe, 0x4b, 0xa3, 0x88, 0x09, 0x2a, 0x7c, 0x16, 0x69, 0x44, 0x6b, 0x5d, 0xfd, 0x19,
	0x77, 0x26, 0x10, 0x75, 0xf8, 0x94, 0x4e, 0x26, 0x90, 0xb8, 0x2c, 0x56, 0x88, 0x53, 0xd0, 0x97,
	0x75, 0x48, 0x7f, 0x22, 0x1e, 0xc3, 0x38, 0xfd, 0x9f, 0x04, 0x68, 0x71, 0x97, 0x79, 0xf0, 0x5e,
	0x02, 0x54, 0xc0, 0x10, 0xbe, 0x78, 0x08, 0x5c, 0xe0, 0x0e, 0x2a, 0x87, 0x20, 0x68, 0xd3, 0x72,
	0xac, 0xb5, 0xfa, 0xe6, 0x4a, 0x77, 0x7f, 0xa3, 0x6b, 0x00, 0x3e, 0x02, 0x41, 0x3d, 0x2a, 0xe8,
	0x50, 0xc1, 0xf0, 0x1a, 0x2a, 0xcb, 0xea, 0x9b, 0xb6, 0x82, 0x5f, 0x94, 0x70, 0xc9, 0x39, 0x40,
	0x4f, 0x8e, 0x67, 0xd5, 0xca, 0x8f, 0x4f, 0x67, 0x55, 0x6b, 0xa8, 0x10, 0xe4, 0x4f, 0x0b, 0xe1,
	0x93, 0xe9, 0x78, 0xcc, 0x22, 0x0e, 0xb8, 0x67, 0xe4, 0x6b, 0x9d, 0xcc, 0x97, 0x22, 0xb2, 0x84,
	0x26, 0xe5, 0xab, 0x25, 0xc7, 0x0e, 0xaa, 0x08, 0xf6, 0x00, 0xa2, 0x66, 0xc9, 0xb1, 0xd6, 0x6a,
	0x06, 0x20, 0x0d, 0xe0, 0xb7, 0x11, 0x4a, 0xa8, 0x80, 0xfb, 0x81, 0x1f, 0xfa, 0xa2, 0x59, 0x56,
	0x8c, 0xd7, 0x24, 0xe3, 0x90, 0x0a, 0xd8, 0x91, 0x8b, 0x79, 0xe7, 0xb5, 0x24, 0x5b, 0xea, 0xa1,
	0xe7, 0x92, 0xe8, 0x7b, 0x49, 0x44, 0x3e, 0x45, 0x0d, 0x99, 0xfd, 0x36, 0x88, 0x4c, 0xcb, 0xb6,
	0xd1, 0xdb, 0xb2, 0x64, 0x2b, 0xa2, 0x73, 0x42, 0xb6, 0x90, 0xed, 0x7b, 0xaa, 0x13, 0xb3, 0x3c,
	0xdb, 0xf7, 0xc8, 0x4f, 0x16, 0xba, 0x92, 0x53, 0x6b, 0xdd, 0xb6, 0x0c, 0xee, 0xeb, 0x39, 0xf7,
	0xbf, 0x28, 0x9a, 0x29, 0x49, 0xe9, 0x1c, 0x92, 0x7c, 0x99, 0x3a, 0xec, 0x5e, 0xec, 0x9d, 0xed,
	0x30, 0x03, 0x30, 0x27, 0x4c, 0xa3, 0x10, 0x46, 0x8a, 0x91, 0xd7, 0x5f, 0x7a, 0xa9, 0xe3, 0x7e,
	0xd1, 0x8e, 0xcb, 0xd8, 0x5f, 0xec, 0x38, 0x13, 0xf1, 0x3f, 0x11, 0xef, 0xb3, 0x54, 0xbc, 0x6d,
	0x08, 0xe0, 0x4c, 0xf1, 0x0c, 0xc0, 0x2b, 0xb8, 0xea, 0x50, 0xcb, 0x93, 0xed, 0x7f, 0xb1, 0x3c,
	0x26, 0xe2, 0x0c, 0x79, 0xcc, 0xa6, 0xed, 0x73, 0x34, 0x3d, 0x4a, 0x9d, 0xbe, 0xe3, 0xf3, 0xfc,
	0x16, 0xbd, 0xf9, 0x4f, 0xa7, 0x9f, 0x08, 0xcf, 0x35, 0x4c, 0xd0, 0xc2, 0xe7, 0x7e, 0x20, 0x20,
	0x39, 0xa5, 0x69, 0x1d, 0x21, 0x47, 0x16, 0xba, 0x5a, 0x24, 0xd1, 0x6d, 0xaf, 0x1b, 0x59, 0x9a,
	0x45, 0x16, 0xb3, 0x69, 0x9d, 0xa6, 0x8d, 0x2a, 0x6a, 0x68, 0x37, 0x6d, 0xa7, 0x74, 0x8a, 0x11,
	0x7e, 0x4e, 0x27, 0x8b, 0x82, 0x9c, 0xcf, 0x09, 0xe4, 0x0f, 0x0b, 0x95, 0x25, 0x23, 0xbe, 0x81,
	0x2a, 0x09, 0x04, 0xf4, 0x40, 0x57, 0x56, 0x53, 0x3b, 0xe5, 0xc2, 0x9d, 0x0b, 0xc3, 0x34, 0x82,
	0x6f, 0xa1, 0xea, 0x84, 0x0a, 0x98, 0xd2, 0x03, 0xad, 0x79, 0x5d, 0x8d, 0x83, 0x74, 0xe9, 0xce,
	0x85, 0x61, 0x16, 0xed, 0xb1, 0xc3, 0xfe, 0xa8, 0xdd, 0x43, 0xd5, 0xbe, 0x23, 0x4b, 0xeb, 0x62,
	0x77, 0x4f, 0x88, 0x98, 0xf7, 0x5c, 0x77, 0x3a, 0x9d, 0x76, 0xb9, 0x48, 0x58, 0x34, 0xf1, 0xc2,
	0xee, 0x98, 0x85, 0xae, 0xc7, 0xc6, 0x5c, 0xbd, 0x3f, 0x10, 0x09, 0x5f, 0xf8, 0xc0, 0x6f, 0xca,
	0x62, 0x36, 0xdf, 0xc0, 0xe4, 0x91, 0x43, 0x7c, 0x8f, 0xf4, 0x1c, 0xb2, 0x45, 0xd6, 0x1d, 0x12,
	0xd1, 0x10, 0xe4, 0xc7, 0x1e, 0x8d, 0xe3, 0x83, 0xce, 0x84, 0x51, 0x41, 0x1e, 0x17, 0xc7, 0x39,
	0x58, 0x4e, 0xef, 0x0b, 0x6e, 0xfc, 0x70, 0x3c, 0xab, 0xd6, 0x8e, 0x8e, 0x67, 0x55, 0xd5, 0x14,
	0xf9, 0xc6, 0x42, 0x15, 0xd5, 0x04, 0xbe, 0xa1, 0x1c, 0x6a, 0xa9, 0xc3, 0x5a, 0x94, 0xe2, 0x5d,
	0x3a, 0x7a, 0x3a, 0xab, 0xda, 0x1f, 0x6e, 0xe7, 0x46, 0xc5, 0xb7, 0x50, 0x59, 0xa6, 0xd1, 0x27,
	0xba, 0x24, 0x41, 0x0d, 0x09, 0x2a, 0xef, 0xd2, 0x10, 0xb2, 0x3b, 0x47, 0x43, 0xc0, 0x2e, 0xaa,
	0x70, 0x41, 0x05, 0xe8, 0x29, 0xbf, 0x72, 0xd8, 0xb7, 0xdf, 0xb5, 0x24, 0xfc, 0x8a, 0x84, 0x57,
	0xee, 0xca, 0x98, 0x1e, 0xfa, 0x0a, 0xd7, 0x5b, 0x7a, 0x5e, 0x70, 0x31, 0x0f, 0x52, 0x0b, 0x7e,
	0x6b, 0xa3, 0xaa, 0xd6, 0xee, 0x3f, 0xad, 0x0e, 0xbf, 0x8f, 0x1a, 0x81, 0xcf, 0x05, 0x44, 0xf7,
	0xa9, 0xe7, 0x25, 0xc0, 0xb9, 0x7a, 0x96, 0x6a, 0x83, 0xd7, 0xe5, 0xa6, 0x15, 0xb9, 0x09, 0xed,
	0xa8, 0x78, 0xdf, 0xf3, 0x12, 0x55, 0x7b, 0xba, 0xfd, 0x72, 0x90, 0xaf, 0x02, 0xe7, 0xf8, 0x1d,
	0x74, 0x69, 0xe4, 0x47, 0x5e, 0x4e, 0x52, 0x51, 0x24, 0xab, 0x92, 0xe4, 0xba, 0x24, 0xb9, 0x38,
	0xf0, 0x23, 0x6f, 0x8e, 0xa2, 0x3e, 0xd2, 0x6b, 0xc0, 0xf9, 0xa9, 0x2a, 0x6d, 0x3e, 0x29, 0xa1,
	0xca, 0xae, 0xf2, 0xf7, 0x77, 0x16, 0x5a, 0x48, 0x9f, 0x6c, 0x7c, 0x2d, 0xbb, 0x07, 0xc6, 0x4f,
	0x86, 0xd6, 0xf2, 0xfc, 0x72, 0x7a, 0xa7, 0x48, 0x70, 0xd8, 0xbf, 0x47, 0xee, 0xa2, 0xe6, 0x0e,
	0xd0, 0x24, 0x72, 0xf6, 0xd8, 0xd4, 0x11, 0xcc, 0x09, 0xe9, 0x03, 0x70, 0xa8, 0xa3, 0xbc, 0xbf,
	0xf5, 0x72, 0x7f, 0x72, 0x48, 0xf6, 0xfd, 0x31, 0x70, 0x57, 0x15, 0x73, 0x33, 0xcd, 0xf0, 0xd5,
	0xef, 0x7f, 0x7d, 0x6d, 0x37, 0x48, 0xcd, 0xdd, 0xdf, 0x70, 0xd5, 0x25, 0xec, 0x59, 0x6d, 0xfc,
	0x01, 0x2a, 0xdd, 0x06, 0x81, 0x71, 0x56, 0x4c, 0xf1, 0x14, 0xb7, 0x96, 0x8c, 0x35, 0x5d, 0xdd,
	0xb2, 0x62, 0xb9, 0x8a, 0x1b, 0x39, 0x8b, 0xfb, 0xc8, 0xf7, 0x1e, 0xe3, 0x21, 0x5a, 0x48, 0xdf,
	0x8b, 0xa2, 0x5d, 0xe3, 0xfd, 0x2a, 0xda, 0x35, 0x9f, 0x15, 0xb2, 0xa2, 0x08, 0x97, 0x5a, 0x73,
	0x84, 0xb2, 0xb6, 0x8f, 0xd1, 0x42, 0x3a, 0x64, 0x0b, 0x4e, 0x63, 0xac, 0x17, 0x9c, 0xe6, 0x2c,
	0xce, 0x8a, 0x6c, 0xcf, 0x17, 0xb9, 0x8d, 0xca, 0xd2, 0x1b, 0x38, 0xef, 0xec, 0xc4, 0xc8, 0x6c,
	0xbd, 0x66, 0x2e, 0x6a, 0xaa, 0x45, 0x45, 0x55, 0xc7, 0x85, 0x6a, 0xad, 0xc6, 0x6f, 0xcf, 0x66,
	0xd5, 0xda, 0xaf, 0xcf, 0xf4, 0xc9, 0x0f, 0x3a, 0x68, 0x75, 0xcc, 0xc2, 0xe2, 0x24, 0x68, 0xec,
	0x4b, 0xaa, 0x38, 0x78, 0x18, 0x8e, 0xfc, 0x68, 0x32, 0xb8, 0xac, 0x0e, 0xe1, 0x13, 0xfd, 0x39,
	0x5a, 0x50, 0xbf, 0x33, 0xdf, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x10, 0x9e, 0x84, 0xe1,
	0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodesClient is the client API for Nodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodesClient interface {
	// Create registers a new Node.
	Create(ctx context.Context, in *NodeCreateRequest, opts ...grpc.CallOption) (*NodeCreateResponse, error)
	// Get reads one Node by ID.
	Get(ctx context.Context, in *NodeGetRequest, opts ...grpc.CallOption) (*NodeGetResponse, error)
	// Update patches a Node by ID.
	Update(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeUpdateResponse, error)
	// Delete removes a Node by ID.
	Delete(ctx context.Context, in *NodeDeleteRequest, opts ...grpc.CallOption) (*NodeDeleteResponse, error)
	// List gets a list of Nodes matching a given set of criteria.
	List(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
}

type nodesClient struct {
	cc *grpc.ClientConn
}

func NewNodesClient(cc *grpc.ClientConn) NodesClient {
	return &nodesClient{cc}
}

func (c *nodesClient) Create(ctx context.Context, in *NodeCreateRequest, opts ...grpc.CallOption) (*NodeCreateResponse, error) {
	out := new(NodeCreateResponse)
	err := c.cc.Invoke(ctx, "/v1.Nodes/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) Get(ctx context.Context, in *NodeGetRequest, opts ...grpc.CallOption) (*NodeGetResponse, error) {
	out := new(NodeGetResponse)
	err := c.cc.Invoke(ctx, "/v1.Nodes/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) Update(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeUpdateResponse, error) {
	out := new(NodeUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.Nodes/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) Delete(ctx context.Context, in *NodeDeleteRequest, opts ...grpc.CallOption) (*NodeDeleteResponse, error) {
	out := new(NodeDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.Nodes/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) List(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, "/v1.Nodes/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodesServer is the server API for Nodes service.
type NodesServer interface {
	// Create registers a new Node.
	Create(context.Context, *NodeCreateRequest) (*NodeCreateResponse, error)
	// Get reads one Node by ID.
	Get(context.Context, *NodeGetRequest) (*NodeGetResponse, error)
	// Update patches a Node by ID.
	Update(context.Context, *NodeUpdateRequest) (*NodeUpdateResponse, error)
	// Delete removes a Node by ID.
	Delete(context.Context, *NodeDeleteRequest) (*NodeDeleteResponse, error)
	// List gets a list of Nodes matching a given set of criteria.
	List(context.Context, *NodeListRequest) (*NodeListResponse, error)
}

// UnimplementedNodesServer can be embedded to have forward compatible implementations.
type UnimplementedNodesServer struct {
}

func (*UnimplementedNodesServer) Create(ctx context.Context, req *NodeCreateRequest) (*NodeCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedNodesServer) Get(ctx context.Context, req *NodeGetRequest) (*NodeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedNodesServer) Update(ctx context.Context, req *NodeUpdateRequest) (*NodeUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedNodesServer) Delete(ctx context.Context, req *NodeDeleteRequest) (*NodeDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedNodesServer) List(ctx context.Context, req *NodeListRequest) (*NodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterNodesServer(s *grpc.Server, srv NodesServer) {
	s.RegisterService(&_Nodes_serviceDesc, srv)
}

func _Nodes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Nodes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).Create(ctx, req.(*NodeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Nodes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).Get(ctx, req.(*NodeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Nodes/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).Update(ctx, req.(*NodeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Nodes/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).Delete(ctx, req.(*NodeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Nodes/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).List(ctx, req.(*NodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nodes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Nodes",
	HandlerType: (*NodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Nodes_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Nodes_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Nodes_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Nodes_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Nodes_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodes.proto",
}
