// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldOptions struct {
	Name              string `protobuf:"bytes,1941300,opt,name=name,proto3" json:"name,omitempty"`
	SqlNullable       bool   `protobuf:"varint,1941301,opt,name=sql_nullable,json=sqlNullable,proto3" json:"sql_nullable,omitempty"`
	ExposeAsPorcelain bool   `protobuf:"varint,1941302,opt,name=expose_as_porcelain,json=exposeAsPorcelain,proto3" json:"expose_as_porcelain,omitempty"`
	// The iterable flag is only valid for repeated fields on RPC output types.
	// If true, the generated RPC method will return the contents of this field
	// as an iterable/generator object. Only one field can have this flag set in
	// the RPC output type.
	Iterable             bool     `protobuf:"varint,1941303,opt,name=iterable,proto3" json:"iterable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldOptions) GetSqlNullable() bool {
	if m != nil {
		return m.SqlNullable
	}
	return false
}

func (m *FieldOptions) GetExposeAsPorcelain() bool {
	if m != nil {
		return m.ExposeAsPorcelain
	}
	return false
}

func (m *FieldOptions) GetIterable() bool {
	if m != nil {
		return m.Iterable
	}
	return false
}

type MessageOptions struct {
	ModelName            string   `protobuf:"bytes,1941300,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Porcelain            bool     `protobuf:"varint,1941301,opt,name=porcelain,proto3" json:"porcelain,omitempty"`
	Error                bool     `protobuf:"varint,1941302,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{1}
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *MessageOptions) GetPorcelain() bool {
	if m != nil {
		return m.Porcelain
	}
	return false
}

func (m *MessageOptions) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type OneofOptions struct {
	ModelName            string   `protobuf:"bytes,1941380,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneofOptions) Reset()         { *m = OneofOptions{} }
func (m *OneofOptions) String() string { return proto.CompactTextString(m) }
func (*OneofOptions) ProtoMessage()    {}
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{2}
}

func (m *OneofOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofOptions.Unmarshal(m, b)
}
func (m *OneofOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofOptions.Marshal(b, m, deterministic)
}
func (m *OneofOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofOptions.Merge(m, src)
}
func (m *OneofOptions) XXX_Size() int {
	return xxx_messageInfo_OneofOptions.Size(m)
}
func (m *OneofOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OneofOptions proto.InternalMessageInfo

func (m *OneofOptions) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

type ServiceOptions struct {
	MainNoun             string   `protobuf:"bytes,1941400,opt,name=main_noun,json=mainNoun,proto3" json:"main_noun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOptions) Reset()         { *m = ServiceOptions{} }
func (m *ServiceOptions) String() string { return proto.CompactTextString(m) }
func (*ServiceOptions) ProtoMessage()    {}
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{3}
}

func (m *ServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOptions.Unmarshal(m, b)
}
func (m *ServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOptions.Marshal(b, m, deterministic)
}
func (m *ServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOptions.Merge(m, src)
}
func (m *ServiceOptions) XXX_Size() int {
	return xxx_messageInfo_ServiceOptions.Size(m)
}
func (m *ServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOptions proto.InternalMessageInfo

func (m *ServiceOptions) GetMainNoun() string {
	if m != nil {
		return m.MainNoun
	}
	return ""
}

var E_FieldOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         1941390,
	Name:          "v1.field_options",
	Tag:           "bytes,1941390,opt,name=field_options",
	Filename:      "options.proto",
}

var E_MessageOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         1941391,
	Name:          "v1.message_options",
	Tag:           "bytes,1941391,opt,name=message_options",
	Filename:      "options.proto",
}

var E_OneofOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.OneofOptions)(nil),
	ExtensionType: (*OneofOptions)(nil),
	Field:         1941381,
	Name:          "v1.oneof_options",
	Tag:           "bytes,1941381,opt,name=oneof_options",
	Filename:      "options.proto",
}

var E_ServiceOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServiceOptions)(nil),
	Field:         1941401,
	Name:          "v1.service_options",
	Tag:           "bytes,1941401,opt,name=service_options",
	Filename:      "options.proto",
}

func init() {
	proto.RegisterType((*FieldOptions)(nil), "v1.FieldOptions")
	proto.RegisterType((*MessageOptions)(nil), "v1.MessageOptions")
	proto.RegisterType((*OneofOptions)(nil), "v1.OneofOptions")
	proto.RegisterType((*ServiceOptions)(nil), "v1.ServiceOptions")
	proto.RegisterExtension(E_FieldOptions)
	proto.RegisterExtension(E_MessageOptions)
	proto.RegisterExtension(E_OneofOptions)
	proto.RegisterExtension(E_ServiceOptions)
}

func init() { proto.RegisterFile("options.proto", fileDescriptor_110d40819f1994f9) }

var fileDescriptor_110d40819f1994f9 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x8e, 0xd4, 0x30,
	0x14, 0x85, 0xb5, 0x08, 0xd0, 0xe4, 0x6e, 0x36, 0x40, 0x40, 0xc8, 0x42, 0xcb, 0xee, 0x2a, 0x34,
	0x54, 0x09, 0x0b, 0xdd, 0x76, 0x50, 0xd0, 0x31, 0x83, 0x82, 0x44, 0x49, 0x94, 0x1f, 0x27, 0xb2,
	0x64, 0xfb, 0x66, 0xec, 0x24, 0xe2, 0x01, 0xa0, 0x85, 0x96, 0x79, 0x0f, 0x7e, 0x3a, 0x78, 0x35,
	0xe4, 0xfc, 0x4d, 0x0c, 0xab, 0x29, 0xef, 0x39, 0xd7, 0xe7, 0x7e, 0x3a, 0x86, 0x13, 0xac, 0x1b,
	0x86, 0x52, 0x87, 0xb5, 0xc2, 0x06, 0xfd, 0x1b, 0xdd, 0xe5, 0xa3, 0x8b, 0x0a, 0xb1, 0xe2, 0x34,
	0xea, 0x95, 0xac, 0x2d, 0xa3, 0x82, 0xea, 0x5c, 0xb1, 0xba, 0x41, 0x35, 0x6c, 0x05, 0xbb, 0x23,
	0x70, 0x5f, 0x33, 0xca, 0x8b, 0xcd, 0xf0, 0xd8, 0x7f, 0x00, 0x37, 0x65, 0x2a, 0x28, 0xf9, 0xfe,
	0xbb, 0xbb, 0x38, 0x7a, 0xea, 0xc4, 0xfd, 0xe4, 0x3f, 0x01, 0x57, 0x6f, 0x79, 0x22, 0x5b, 0xce,
	0xd3, 0x8c, 0x53, 0xf2, 0xa3, 0x77, 0x57, 0xf1, 0xb1, 0xde, 0xf2, 0xf5, 0x28, 0xfa, 0xcf, 0xe0,
	0x3e, 0xfd, 0x58, 0xa3, 0xa6, 0x49, 0xaa, 0x93, 0x1a, 0x55, 0x4e, 0x79, 0xca, 0x24, 0xf9, 0x39,
	0xee, 0xde, 0x1b, 0xcc, 0x97, 0xfa, 0xed, 0x64, 0xf9, 0xa7, 0xb0, 0x62, 0x0d, 0x55, 0x7d, 0xe4,
	0xaf, 0x71, 0x6d, 0x56, 0x02, 0x06, 0xde, 0x1b, 0xaa, 0x75, 0x5a, 0xd1, 0x09, 0xee, 0x1c, 0x40,
	0x60, 0x41, 0x79, 0x62, 0x21, 0x3a, 0xbd, 0xb6, 0x36, 0x9c, 0x67, 0xe0, 0xec, 0x0f, 0x4f, 0x90,
	0x7b, 0xc9, 0x7f, 0x08, 0xb7, 0xa8, 0x52, 0xa8, 0x66, 0xa8, 0x61, 0x0c, 0x22, 0x70, 0x37, 0x92,
	0x62, 0x79, 0xfd, 0xa1, 0x4f, 0x7f, 0xfe, 0x3d, 0x14, 0x44, 0xe0, 0xbd, 0xa3, 0xaa, 0x63, 0xf9,
	0xcc, 0xf6, 0x18, 0x1c, 0x91, 0x32, 0x99, 0x48, 0x6c, 0x25, 0xf9, 0x36, 0xbe, 0x58, 0x19, 0x69,
	0x8d, 0xad, 0xbc, 0x7a, 0x0f, 0x27, 0xa5, 0xe9, 0x39, 0xc1, 0x69, 0x3f, 0x1c, 0x3e, 0x27, 0x9c,
	0x3e, 0x27, 0x5c, 0xfe, 0x03, 0xf9, 0xd2, 0x27, 0x1c, 0x3f, 0xbf, 0x1b, 0x76, 0x97, 0x96, 0x13,
	0xbb, 0xe5, 0x62, 0xba, 0xfa, 0x00, 0x77, 0xc4, 0x50, 0xd2, 0x9c, 0x7c, 0xfe, 0x5f, 0xb2, 0x5d,
	0x23, 0xf9, 0x3a, 0x66, 0xfb, 0x26, 0xdb, 0xf6, 0x62, 0x4f, 0x58, 0xb3, 0xe1, 0x46, 0xd3, 0xcc,
	0x01, 0xee, 0x65, 0x73, 0xe4, 0xf3, 0x92, 0x7b, 0xe9, 0xc4, 0x2e, 0x2e, 0x26, 0xc3, 0xad, 0x87,
	0x02, 0x0f, 0x70, 0xdb, 0x15, 0x93, 0xdd, 0x92, 0xdb, 0xf6, 0x62, 0x4f, 0x5b, 0xf3, 0xab, 0x33,
	0x38, 0xcd, 0x51, 0x84, 0xba, 0x51, 0x28, 0xab, 0x42, 0x84, 0x69, 0xcd, 0xcc, 0xab, 0x9a, 0xb7,
	0x22, 0x63, 0xb2, 0xca, 0x6e, 0xf7, 0x47, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x3f,
	0x54, 0x37, 0x36, 0x03, 0x00, 0x00,
}
