// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roles.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RoleCreateRequest specifies what kind of Roles that should be registered in
// the organizations fleet. Note that a Role must be either a Relay or a
// Gateway.
type RoleCreateRequest struct {
	Meta                 *CreateRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Roles                []*Role                `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoleCreateRequest) Reset()         { *m = RoleCreateRequest{} }
func (m *RoleCreateRequest) String() string { return proto.CompactTextString(m) }
func (*RoleCreateRequest) ProtoMessage()    {}
func (*RoleCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{0}
}

func (m *RoleCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateRequest.Unmarshal(m, b)
}
func (m *RoleCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateRequest.Marshal(b, m, deterministic)
}
func (m *RoleCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateRequest.Merge(m, src)
}
func (m *RoleCreateRequest) XXX_Size() int {
	return xxx_messageInfo_RoleCreateRequest.Size(m)
}
func (m *RoleCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateRequest proto.InternalMessageInfo

func (m *RoleCreateRequest) GetMeta() *CreateRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleCreateRequest) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// RoleCreateResponse reports how the Roles were created in the system. It can
// communicate partial successes or failures.
type RoleCreateResponse struct {
	Meta                 *CreateResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Roles                []*Role                 `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RoleCreateResponse) Reset()         { *m = RoleCreateResponse{} }
func (m *RoleCreateResponse) String() string { return proto.CompactTextString(m) }
func (*RoleCreateResponse) ProtoMessage()    {}
func (*RoleCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{1}
}

func (m *RoleCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateResponse.Unmarshal(m, b)
}
func (m *RoleCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateResponse.Marshal(b, m, deterministic)
}
func (m *RoleCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateResponse.Merge(m, src)
}
func (m *RoleCreateResponse) XXX_Size() int {
	return xxx_messageInfo_RoleCreateResponse.Size(m)
}
func (m *RoleCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateResponse proto.InternalMessageInfo

func (m *RoleCreateResponse) GetMeta() *CreateResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleCreateResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// RoleGetRequest specifies which Role to retrieve.
type RoleGetRequest struct {
	Meta                 *GetRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Id                   string              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RoleGetRequest) Reset()         { *m = RoleGetRequest{} }
func (m *RoleGetRequest) String() string { return proto.CompactTextString(m) }
func (*RoleGetRequest) ProtoMessage()    {}
func (*RoleGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{2}
}

func (m *RoleGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGetRequest.Unmarshal(m, b)
}
func (m *RoleGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGetRequest.Marshal(b, m, deterministic)
}
func (m *RoleGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGetRequest.Merge(m, src)
}
func (m *RoleGetRequest) XXX_Size() int {
	return xxx_messageInfo_RoleGetRequest.Size(m)
}
func (m *RoleGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGetRequest proto.InternalMessageInfo

func (m *RoleGetRequest) GetMeta() *GetRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// RoleGetResponse returns a requested Role.
type RoleGetResponse struct {
	Meta                 *GetResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Role                 *Role                `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RoleGetResponse) Reset()         { *m = RoleGetResponse{} }
func (m *RoleGetResponse) String() string { return proto.CompactTextString(m) }
func (*RoleGetResponse) ProtoMessage()    {}
func (*RoleGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{3}
}

func (m *RoleGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGetResponse.Unmarshal(m, b)
}
func (m *RoleGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGetResponse.Marshal(b, m, deterministic)
}
func (m *RoleGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGetResponse.Merge(m, src)
}
func (m *RoleGetResponse) XXX_Size() int {
	return xxx_messageInfo_RoleGetResponse.Size(m)
}
func (m *RoleGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGetResponse proto.InternalMessageInfo

func (m *RoleGetResponse) GetMeta() *GetResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleGetResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

// RoleUpdateRequest identifies a Role by ID and provides fields to update on
// that Role record.
type RoleUpdateRequest struct {
	Meta                 *UpdateRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Role                 *Role                  `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoleUpdateRequest) Reset()         { *m = RoleUpdateRequest{} }
func (m *RoleUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateRequest) ProtoMessage()    {}
func (*RoleUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{4}
}

func (m *RoleUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateRequest.Unmarshal(m, b)
}
func (m *RoleUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateRequest.Marshal(b, m, deterministic)
}
func (m *RoleUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateRequest.Merge(m, src)
}
func (m *RoleUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateRequest.Size(m)
}
func (m *RoleUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateRequest proto.InternalMessageInfo

func (m *RoleUpdateRequest) GetMeta() *UpdateRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoleUpdateRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

// RoleUpdateResponse returns the fields of a Role after it has been updated by
// a RoleUpdateRequest.
type RoleUpdateResponse struct {
	Meta                 *UpdateResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Role                 *Role                   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RoleUpdateResponse) Reset()         { *m = RoleUpdateResponse{} }
func (m *RoleUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateResponse) ProtoMessage()    {}
func (*RoleUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{5}
}

func (m *RoleUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateResponse.Unmarshal(m, b)
}
func (m *RoleUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateResponse.Marshal(b, m, deterministic)
}
func (m *RoleUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateResponse.Merge(m, src)
}
func (m *RoleUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateResponse.Size(m)
}
func (m *RoleUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateResponse proto.InternalMessageInfo

func (m *RoleUpdateResponse) GetMeta() *UpdateResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleUpdateResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

// RoleDeleteRequest identifies a Role by ID to delete.
type RoleDeleteRequest struct {
	Meta                 *DeleteRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Id                   string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoleDeleteRequest) Reset()         { *m = RoleDeleteRequest{} }
func (m *RoleDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RoleDeleteRequest) ProtoMessage()    {}
func (*RoleDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{6}
}

func (m *RoleDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDeleteRequest.Unmarshal(m, b)
}
func (m *RoleDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RoleDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDeleteRequest.Merge(m, src)
}
func (m *RoleDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RoleDeleteRequest.Size(m)
}
func (m *RoleDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDeleteRequest proto.InternalMessageInfo

func (m *RoleDeleteRequest) GetMeta() *DeleteRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// RoleDeleteResponse returns information about a Role that was deleted.
type RoleDeleteResponse struct {
	Meta                 *DeleteResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RoleDeleteResponse) Reset()         { *m = RoleDeleteResponse{} }
func (m *RoleDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RoleDeleteResponse) ProtoMessage()    {}
func (*RoleDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{7}
}

func (m *RoleDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDeleteResponse.Unmarshal(m, b)
}
func (m *RoleDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RoleDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDeleteResponse.Merge(m, src)
}
func (m *RoleDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RoleDeleteResponse.Size(m)
}
func (m *RoleDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDeleteResponse proto.InternalMessageInfo

func (m *RoleDeleteResponse) GetMeta() *DeleteResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

// RoleListRequest specifies criteria for retrieving a list of Roles.
type RoleListRequest struct {
	Meta                 *ListRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Filter               string               `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RoleListRequest) Reset()         { *m = RoleListRequest{} }
func (m *RoleListRequest) String() string { return proto.CompactTextString(m) }
func (*RoleListRequest) ProtoMessage()    {}
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{8}
}

func (m *RoleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListRequest.Unmarshal(m, b)
}
func (m *RoleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListRequest.Marshal(b, m, deterministic)
}
func (m *RoleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListRequest.Merge(m, src)
}
func (m *RoleListRequest) XXX_Size() int {
	return xxx_messageInfo_RoleListRequest.Size(m)
}
func (m *RoleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListRequest proto.InternalMessageInfo

func (m *RoleListRequest) GetMeta() *ListRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// RoleListResponse returns a list of Roles that meet the criteria of a
// RoleListRequest.
type RoleListResponse struct {
	Meta                 *ListResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Roles                []*Role               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoleListResponse) Reset()         { *m = RoleListResponse{} }
func (m *RoleListResponse) String() string { return proto.CompactTextString(m) }
func (*RoleListResponse) ProtoMessage()    {}
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{9}
}

func (m *RoleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListResponse.Unmarshal(m, b)
}
func (m *RoleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListResponse.Marshal(b, m, deterministic)
}
func (m *RoleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListResponse.Merge(m, src)
}
func (m *RoleListResponse) XXX_Size() int {
	return xxx_messageInfo_RoleListResponse.Size(m)
}
func (m *RoleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListResponse proto.InternalMessageInfo

func (m *RoleListResponse) GetMeta() *ListResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleListResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// RoleBatchUpdateRequest specifies a list of Roles and fields to update within
// those Roles.
type RoleBatchUpdateRequest struct {
	Meta                 *BatchUpdateRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Roles                []*Role                     `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RoleBatchUpdateRequest) Reset()         { *m = RoleBatchUpdateRequest{} }
func (m *RoleBatchUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RoleBatchUpdateRequest) ProtoMessage()    {}
func (*RoleBatchUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{10}
}

func (m *RoleBatchUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBatchUpdateRequest.Unmarshal(m, b)
}
func (m *RoleBatchUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBatchUpdateRequest.Marshal(b, m, deterministic)
}
func (m *RoleBatchUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBatchUpdateRequest.Merge(m, src)
}
func (m *RoleBatchUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_RoleBatchUpdateRequest.Size(m)
}
func (m *RoleBatchUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBatchUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBatchUpdateRequest proto.InternalMessageInfo

func (m *RoleBatchUpdateRequest) GetMeta() *BatchUpdateRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleBatchUpdateRequest) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// RoleBatchUpdateResponse returns a list of Roles updated via
// RoleBatchUpdateRequest.
type RoleBatchUpdateResponse struct {
	Meta                 *BatchUpdateResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Roles                []*Role                      `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RoleBatchUpdateResponse) Reset()         { *m = RoleBatchUpdateResponse{} }
func (m *RoleBatchUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*RoleBatchUpdateResponse) ProtoMessage()    {}
func (*RoleBatchUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{11}
}

func (m *RoleBatchUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBatchUpdateResponse.Unmarshal(m, b)
}
func (m *RoleBatchUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBatchUpdateResponse.Marshal(b, m, deterministic)
}
func (m *RoleBatchUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBatchUpdateResponse.Merge(m, src)
}
func (m *RoleBatchUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_RoleBatchUpdateResponse.Size(m)
}
func (m *RoleBatchUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBatchUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBatchUpdateResponse proto.InternalMessageInfo

func (m *RoleBatchUpdateResponse) GetMeta() *BatchUpdateResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleBatchUpdateResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// RoleBatchDeleteRequest specifies a list of Roles to delete by ID.
type RoleBatchDeleteRequest struct {
	Meta                 *BatchDeleteRequestMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Ids                  []string                    `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RoleBatchDeleteRequest) Reset()         { *m = RoleBatchDeleteRequest{} }
func (m *RoleBatchDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RoleBatchDeleteRequest) ProtoMessage()    {}
func (*RoleBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{12}
}

func (m *RoleBatchDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBatchDeleteRequest.Unmarshal(m, b)
}
func (m *RoleBatchDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBatchDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RoleBatchDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBatchDeleteRequest.Merge(m, src)
}
func (m *RoleBatchDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RoleBatchDeleteRequest.Size(m)
}
func (m *RoleBatchDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBatchDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBatchDeleteRequest proto.InternalMessageInfo

func (m *RoleBatchDeleteRequest) GetMeta() *BatchDeleteRequestMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RoleBatchDeleteRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

// RoleBatchDeleteResponse returns information about Roles deleted via a
// RoleBatchDeleteRequest.
type RoleBatchDeleteResponse struct {
	Meta                 *BatchDeleteResponseMetadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RoleBatchDeleteResponse) Reset()         { *m = RoleBatchDeleteResponse{} }
func (m *RoleBatchDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RoleBatchDeleteResponse) ProtoMessage()    {}
func (*RoleBatchDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{13}
}

func (m *RoleBatchDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBatchDeleteResponse.Unmarshal(m, b)
}
func (m *RoleBatchDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBatchDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RoleBatchDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBatchDeleteResponse.Merge(m, src)
}
func (m *RoleBatchDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RoleBatchDeleteResponse.Size(m)
}
func (m *RoleBatchDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBatchDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBatchDeleteResponse proto.InternalMessageInfo

func (m *RoleBatchDeleteResponse) GetMeta() *BatchDeleteResponseMetadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

// Role is a domain object --
type Role struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Composite            bool     `protobuf:"varint,3,opt,name=composite,proto3" json:"composite,omitempty"`
	Roles                []*Role  `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96358c61fe6d5ae, []int{14}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetComposite() bool {
	if m != nil {
		return m.Composite
	}
	return false
}

func (m *Role) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleCreateRequest)(nil), "v1.RoleCreateRequest")
	proto.RegisterType((*RoleCreateResponse)(nil), "v1.RoleCreateResponse")
	proto.RegisterType((*RoleGetRequest)(nil), "v1.RoleGetRequest")
	proto.RegisterType((*RoleGetResponse)(nil), "v1.RoleGetResponse")
	proto.RegisterType((*RoleUpdateRequest)(nil), "v1.RoleUpdateRequest")
	proto.RegisterType((*RoleUpdateResponse)(nil), "v1.RoleUpdateResponse")
	proto.RegisterType((*RoleDeleteRequest)(nil), "v1.RoleDeleteRequest")
	proto.RegisterType((*RoleDeleteResponse)(nil), "v1.RoleDeleteResponse")
	proto.RegisterType((*RoleListRequest)(nil), "v1.RoleListRequest")
	proto.RegisterType((*RoleListResponse)(nil), "v1.RoleListResponse")
	proto.RegisterType((*RoleBatchUpdateRequest)(nil), "v1.RoleBatchUpdateRequest")
	proto.RegisterType((*RoleBatchUpdateResponse)(nil), "v1.RoleBatchUpdateResponse")
	proto.RegisterType((*RoleBatchDeleteRequest)(nil), "v1.RoleBatchDeleteRequest")
	proto.RegisterType((*RoleBatchDeleteResponse)(nil), "v1.RoleBatchDeleteResponse")
	proto.RegisterType((*Role)(nil), "v1.Role")
}

func init() { proto.RegisterFile("roles.proto", fileDescriptor_b96358c61fe6d5ae) }

var fileDescriptor_b96358c61fe6d5ae = []byte{
	// 890 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6b, 0x3b, 0x45,
	0x1c, 0x67, 0x37, 0xaf, 0x5f, 0x26, 0x9a, 0xb6, 0x93, 0x9a, 0xa6, 0xdb, 0xa2, 0xeb, 0x54, 0x30,
	0xc4, 0x26, 0x4b, 0xa3, 0x58, 0xc8, 0x45, 0xfa, 0xc0, 0x22, 0x54, 0x85, 0x48, 0x41, 0xa1, 0x08,
	0xd3, 0xec, 0x34, 0x59, 0x4d, 0x76, 0xd6, 0xdd, 0x31, 0x51, 0x4a, 0x41, 0x3c, 0x48, 0xcf, 0xf5,
	0xe8, 0x4d, 0x10, 0x3c, 0x2a, 0xbd, 0xf8, 0x7f, 0xf8, 0x2f, 0xf8, 0x17, 0xd8, 0x8b, 0x78, 0x92,
	0x79, 0x6c, 0x36, 0x93, 0x64, 0x5b, 0xeb, 0xe3, 0xd4, 0xee, 0xcc, 0x67, 0x3e, 0x8f, 0xf9, 0x7e,
	0x67, 0x26, 0xa0, 0x14, 0xd2, 0x21, 0x89, 0x5a, 0x41, 0x48, 0x19, 0x85, 0xe6, 0x78, 0xcf, 0xda,
	0xee, 0x53, 0xda, 0x1f, 0x12, 0x07, 0x07, 0x9e, 0x83, 0x7d, 0x9f, 0x32, 0xcc, 0x3c, 0xea, 0x2b,
	0x84, 0xb5, 0x2b, 0xfe, 0xf4, 0x9a, 0x7d, 0xe2, 0x37, 0xa3, 0x09, 0xee, 0xf7, 0x49, 0xe8, 0xd0,
	0x40, 0x20, 0x96, 0xa0, 0x9f, 0x57, 0x53, 0xea, 0x13, 0x44, 0x01, 0xe9, 0xc9, 0xff, 0x91, 0x0f,
	0xd6, 0xba, 0x74, 0x48, 0x8e, 0x42, 0x82, 0x19, 0xe9, 0x92, 0xcf, 0x3e, 0x27, 0x11, 0x83, 0x4d,
	0x90, 0x1d, 0x11, 0x86, 0x6b, 0x86, 0x6d, 0xd4, 0x4b, 0xed, 0xcd, 0xd6, 0x78, 0xaf, 0xa5, 0x01,
	0xde, 0x25, 0x0c, 0xbb, 0x98, 0xe1, 0xae, 0x80, 0xc1, 0x06, 0xc8, 0x09, 0xf7, 0x35, 0xd3, 0xce,
	0xd4, 0x4b, 0xed, 0x67, 0x1c, 0xcf, 0x49, 0x0f, 0xc1, 0xef, 0x7f, 0xdc, 0x15, 0x72, 0x3f, 0xdd,
	0xdf, 0x15, 0x8c, 0xae, 0x84, 0xa0, 0x1b, 0x03, 0xc0, 0x59, 0xc1, 0x28, 0xa0, 0x7e, 0x44, 0x60,
	0x47, 0x53, 0xb4, 0x66, 0x15, 0x25, 0x22, 0x96, 0xd4, 0x38, 0x9f, 0x2c, 0xdf, 0x01, 0x7f, 0xf2,
	0xa1, 0x1f, 0xf9, 0x10, 0xfa, 0x10, 0x94, 0x39, 0xec, 0x84, 0xb0, 0x38, 0x77, 0x43, 0x73, 0x51,
	0xe5, 0x44, 0xc9, 0xec, 0x5c, 0x68, 0x0b, 0x98, 0x9e, 0x5b, 0x33, 0x6d, 0xa3, 0x5e, 0xd4, 0x84,
	0x4c, 0xcf, 0x45, 0x5f, 0x19, 0x60, 0x65, 0x4a, 0xad, 0x12, 0xee, 0x6b, 0xdc, 0x1b, 0x53, 0xee,
	0x47, 0xe3, 0xd5, 0x41, 0x96, 0x7b, 0x17, 0x52, 0x69, 0xe9, 0x04, 0x42, 0x0b, 0x77, 0x63, 0xc8,
	0xc2, 0x9e, 0x05, 0xee, 0xc3, 0x85, 0xd5, 0x00, 0x7f, 0x3f, 0xe3, 0xd4, 0x56, 0xe6, 0x31, 0x5b,
	0xe8, 0x1b, 0x55, 0xf2, 0x58, 0x29, 0xbd, 0xe4, 0x3a, 0xe2, 0x3f, 0xdf, 0x93, 0x8f, 0xe5, 0x96,
	0x1c, 0x93, 0x21, 0x79, 0x70, 0x4b, 0x34, 0xc0, 0x13, 0xca, 0x7e, 0x2e, 0x73, 0xc6, 0xcb, 0xd3,
	0x73, 0xea, 0x88, 0xf4, 0x9c, 0x9a, 0xfb, 0x0b, 0xd9, 0x53, 0xa7, 0x5e, 0x34, 0xed, 0xd7, 0xd7,
	0x16, 0x7b, 0x6a, 0x66, 0x7a, 0xce, 0x39, 0x02, 0xf9, 0x4b, 0x6f, 0xc8, 0x48, 0xb8, 0xc4, 0xbd,
	0x9a, 0x41, 0xd7, 0x60, 0x35, 0xd1, 0x50, 0xfe, 0x77, 0x35, 0x91, 0x5a, 0x22, 0xa2, 0xbb, 0x57,
	0x2a, 0x4e, 0xda, 0x61, 0x5c, 0xe1, 0x72, 0x40, 0xc8, 0xfd, 0x92, 0x76, 0x22, 0xbf, 0x00, 0x55,
	0x81, 0xc5, 0xac, 0x37, 0xd0, 0x1b, 0xb7, 0xad, 0x99, 0x78, 0x91, 0xb3, 0x2e, 0xa2, 0xfe, 0xc5,
	0xb5, 0x74, 0x6b, 0x80, 0x8d, 0x05, 0x69, 0xb5, 0x01, 0x6f, 0x69, 0xda, 0x2f, 0x2d, 0x68, 0xff,
	0x6f, 0x17, 0xd4, 0x27, 0x33, 0xdb, 0xa1, 0x37, 0x6d, 0xda, 0x76, 0x3c, 0xd4, 0xb9, 0xdb, 0x20,
	0xe3, 0xb9, 0xd2, 0x83, 0x5e, 0x7c, 0x3e, 0x8c, 0x2e, 0x67, 0xf2, 0xcf, 0x35, 0x70, 0x5a, 0xfe,
	0x7f, 0xd4, 0xc5, 0x3f, 0x9b, 0x20, 0xcb, 0x85, 0xe0, 0xcb, 0xe2, 0x20, 0x19, 0xa2, 0x15, 0xd7,
	0xf8, 0x92, 0xe7, 0xbe, 0xbf, 0xbf, 0x2b, 0x98, 0xef, 0x1c, 0x27, 0x57, 0xcc, 0xab, 0x20, 0xeb,
	0xe3, 0x11, 0x51, 0xfd, 0x5a, 0xe1, 0xa0, 0x32, 0x07, 0x65, 0xdf, 0xc3, 0x23, 0xa2, 0x04, 0x38,
	0x00, 0xbe, 0x09, 0x8a, 0x3d, 0x3a, 0x0a, 0x68, 0xe4, 0x31, 0x79, 0x21, 0x3d, 0x3b, 0xac, 0x71,
	0x74, 0x85, 0xa3, 0x8b, 0x47, 0xf1, 0x94, 0x5c, 0x92, 0x40, 0xe1, 0x1b, 0x71, 0x61, 0xb2, 0x73,
	0x85, 0x59, 0xe7, 0xab, 0x57, 0xf8, 0xea, 0x1c, 0xff, 0x8e, 0xb4, 0x12, 0xd1, 0xdb, 0x83, 0x8b,
	0x46, 0x07, 0x14, 0x0e, 0x6c, 0x3e, 0xd7, 0x82, 0xce, 0x80, 0xb1, 0x20, 0xea, 0x38, 0xce, 0x64,
	0x32, 0x69, 0x45, 0x2c, 0xa4, 0x7e, 0xdf, 0x1d, 0xb5, 0x7a, 0x74, 0xe4, 0xb8, 0xb4, 0x17, 0x89,
	0x07, 0x9c, 0xf8, 0xcc, 0x63, 0x1e, 0x89, 0x76, 0xf8, 0x8a, 0xf6, 0x2b, 0x10, 0x5d, 0xd9, 0xc8,
	0x73, 0x51, 0xc7, 0x46, 0xfb, 0x68, 0xd7, 0x46, 0x3c, 0x04, 0xff, 0x18, 0xe0, 0x20, 0xf8, 0xb2,
	0xd9, 0xa7, 0x98, 0xa1, 0xeb, 0x64, 0xcf, 0xda, 0xdf, 0xe5, 0x80, 0xb4, 0x01, 0x7f, 0x30, 0x40,
	0x5e, 0xbe, 0x8b, 0xf0, 0x85, 0xd8, 0xac, 0xf6, 0x32, 0x5b, 0xd5, 0xf9, 0x61, 0x59, 0x1d, 0x34,
	0xbc, 0x3d, 0x38, 0x43, 0x1f, 0x80, 0xda, 0x29, 0xc1, 0xa1, 0x6f, 0x0f, 0xe8, 0xc4, 0x66, 0xd4,
	0x1e, 0xe1, 0x4f, 0x89, 0x8d, 0x45, 0x0c, 0xb8, 0xff, 0x78, 0x8a, 0x88, 0x84, 0x63, 0xaf, 0x47,
	0x22, 0x47, 0x98, 0xd9, 0x91, 0x0a, 0x5f, 0xff, 0xfa, 0xdb, 0xb7, 0x66, 0x19, 0x15, 0x9d, 0xf1,
	0x9e, 0x23, 0xf7, 0xc7, 0x68, 0xc0, 0xb7, 0x41, 0xe6, 0x84, 0x30, 0x08, 0x63, 0x33, 0xc9, 0x2b,
	0x6a, 0x55, 0xb4, 0x31, 0xe5, 0xae, 0x2a, 0x58, 0x56, 0x61, 0x79, 0xca, 0xe2, 0x5c, 0x79, 0xee,
	0x35, 0xec, 0x82, 0xbc, 0x3c, 0x65, 0x49, 0x5c, 0xed, 0xc4, 0x27, 0x71, 0xf5, 0xc3, 0x88, 0x36,
	0x05, 0x61, 0xc5, 0x9a, 0x23, 0xe4, 0xde, 0xde, 0x07, 0x79, 0xd9, 0xb9, 0x09, 0xa7, 0x76, 0x6c,
	0x12, 0x4e, 0xbd, 0xc1, 0x63, 0x93, 0x8d, 0x79, 0x93, 0xc7, 0x20, 0xcb, 0x2f, 0x44, 0x38, 0x4d,
	0x36, 0x73, 0x07, 0x5b, 0xeb, 0xfa, 0xa0, 0xa2, 0x5a, 0x13, 0x54, 0x25, 0x98, 0xec, 0x1a, 0x3c,
	0x07, 0xa5, 0x99, 0x5b, 0x05, 0x5a, 0xd3, 0x5e, 0x5c, 0xb8, 0xe6, 0xac, 0xad, 0xa5, 0x73, 0x8a,
	0x7a, 0x5d, 0x16, 0xc4, 0xd2, 0x0b, 0xf2, 0x91, 0x62, 0x57, 0xc9, 0x75, 0x76, 0x3d, 0xfe, 0xd6,
	0xd2, 0x39, 0xdd, 0x78, 0x23, 0x61, 0xbf, 0xc8, 0x8b, 0x1f, 0x92, 0xaf, 0xff, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0xa2, 0xa2, 0xc6, 0xc2, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RolesClient is the client API for Roles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RolesClient interface {
	// Create registers a new role.
	Create(ctx context.Context, in *RoleCreateRequest, opts ...grpc.CallOption) (*RoleCreateResponse, error)
	// Get reads one role by ID.
	Get(ctx context.Context, in *RoleGetRequest, opts ...grpc.CallOption) (*RoleGetResponse, error)
	// Update patches a Role by ID.
	Update(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*RoleUpdateResponse, error)
	// Delete removes a Role by ID.
	Delete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*RoleDeleteResponse, error)
	// List is a batched Get call.
	List(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
	// BatchUpdate is a batched Update call.
	BatchUpdate(ctx context.Context, in *RoleBatchUpdateRequest, opts ...grpc.CallOption) (*RoleBatchUpdateResponse, error)
	// BatchDelete is a batched Delete call.
	BatchDelete(ctx context.Context, in *RoleBatchDeleteRequest, opts ...grpc.CallOption) (*RoleBatchDeleteResponse, error)
}

type rolesClient struct {
	cc *grpc.ClientConn
}

func NewRolesClient(cc *grpc.ClientConn) RolesClient {
	return &rolesClient{cc}
}

func (c *rolesClient) Create(ctx context.Context, in *RoleCreateRequest, opts ...grpc.CallOption) (*RoleCreateResponse, error) {
	out := new(RoleCreateResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) Get(ctx context.Context, in *RoleGetRequest, opts ...grpc.CallOption) (*RoleGetResponse, error) {
	out := new(RoleGetResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) Update(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*RoleUpdateResponse, error) {
	out := new(RoleUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) Delete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*RoleDeleteResponse, error) {
	out := new(RoleDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) List(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	out := new(RoleListResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) BatchUpdate(ctx context.Context, in *RoleBatchUpdateRequest, opts ...grpc.CallOption) (*RoleBatchUpdateResponse, error) {
	out := new(RoleBatchUpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/BatchUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) BatchDelete(ctx context.Context, in *RoleBatchDeleteRequest, opts ...grpc.CallOption) (*RoleBatchDeleteResponse, error) {
	out := new(RoleBatchDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.Roles/BatchDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolesServer is the server API for Roles service.
type RolesServer interface {
	// Create registers a new role.
	Create(context.Context, *RoleCreateRequest) (*RoleCreateResponse, error)
	// Get reads one role by ID.
	Get(context.Context, *RoleGetRequest) (*RoleGetResponse, error)
	// Update patches a Role by ID.
	Update(context.Context, *RoleUpdateRequest) (*RoleUpdateResponse, error)
	// Delete removes a Role by ID.
	Delete(context.Context, *RoleDeleteRequest) (*RoleDeleteResponse, error)
	// List is a batched Get call.
	List(context.Context, *RoleListRequest) (*RoleListResponse, error)
	// BatchUpdate is a batched Update call.
	BatchUpdate(context.Context, *RoleBatchUpdateRequest) (*RoleBatchUpdateResponse, error)
	// BatchDelete is a batched Delete call.
	BatchDelete(context.Context, *RoleBatchDeleteRequest) (*RoleBatchDeleteResponse, error)
}

// UnimplementedRolesServer can be embedded to have forward compatible implementations.
type UnimplementedRolesServer struct {
}

func (*UnimplementedRolesServer) Create(ctx context.Context, req *RoleCreateRequest) (*RoleCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedRolesServer) Get(ctx context.Context, req *RoleGetRequest) (*RoleGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRolesServer) Update(ctx context.Context, req *RoleUpdateRequest) (*RoleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedRolesServer) Delete(ctx context.Context, req *RoleDeleteRequest) (*RoleDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedRolesServer) List(ctx context.Context, req *RoleListRequest) (*RoleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedRolesServer) BatchUpdate(ctx context.Context, req *RoleBatchUpdateRequest) (*RoleBatchUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdate not implemented")
}
func (*UnimplementedRolesServer) BatchDelete(ctx context.Context, req *RoleBatchDeleteRequest) (*RoleBatchDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDelete not implemented")
}

func RegisterRolesServer(s *grpc.Server, srv RolesServer) {
	s.RegisterService(&_Roles_serviceDesc, srv)
}

func _Roles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Create(ctx, req.(*RoleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Get(ctx, req.(*RoleGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Update(ctx, req.(*RoleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Delete(ctx, req.(*RoleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).List(ctx, req.(*RoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_BatchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBatchUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).BatchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/BatchUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).BatchUpdate(ctx, req.(*RoleBatchUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Roles/BatchDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).BatchDelete(ctx, req.(*RoleBatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Roles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Roles",
	HandlerType: (*RolesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Roles_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Roles_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Roles_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Roles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Roles_List_Handler,
		},
		{
			MethodName: "BatchUpdate",
			Handler:    _Roles_BatchUpdate_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _Roles_BatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roles.proto",
}
