// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDetail struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}

func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(m, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// CreateRequestMetadata
type CreateRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequestMetadata) Reset()         { *m = CreateRequestMetadata{} }
func (m *CreateRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*CreateRequestMetadata) ProtoMessage()    {}
func (*CreateRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{1}
}

func (m *CreateRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestMetadata.Unmarshal(m, b)
}
func (m *CreateRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestMetadata.Marshal(b, m, deterministic)
}
func (m *CreateRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestMetadata.Merge(m, src)
}
func (m *CreateRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_CreateRequestMetadata.Size(m)
}
func (m *CreateRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestMetadata proto.InternalMessageInfo

// CreateResponseMetadata
type CreateResponseMetadata struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponseMetadata) Reset()         { *m = CreateResponseMetadata{} }
func (m *CreateResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*CreateResponseMetadata) ProtoMessage()    {}
func (*CreateResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{2}
}

func (m *CreateResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponseMetadata.Unmarshal(m, b)
}
func (m *CreateResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponseMetadata.Marshal(b, m, deterministic)
}
func (m *CreateResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponseMetadata.Merge(m, src)
}
func (m *CreateResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_CreateResponseMetadata.Size(m)
}
func (m *CreateResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponseMetadata proto.InternalMessageInfo

func (m *CreateResponseMetadata) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

// GetRequestMetadata
type GetRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequestMetadata) Reset()         { *m = GetRequestMetadata{} }
func (m *GetRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*GetRequestMetadata) ProtoMessage()    {}
func (*GetRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{3}
}

func (m *GetRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequestMetadata.Unmarshal(m, b)
}
func (m *GetRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequestMetadata.Marshal(b, m, deterministic)
}
func (m *GetRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequestMetadata.Merge(m, src)
}
func (m *GetRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_GetRequestMetadata.Size(m)
}
func (m *GetRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequestMetadata proto.InternalMessageInfo

// GetResponseMetadata
type GetResponseMetadata struct {
	Found                int64    `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponseMetadata) Reset()         { *m = GetResponseMetadata{} }
func (m *GetResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*GetResponseMetadata) ProtoMessage()    {}
func (*GetResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{4}
}

func (m *GetResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponseMetadata.Unmarshal(m, b)
}
func (m *GetResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponseMetadata.Marshal(b, m, deterministic)
}
func (m *GetResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponseMetadata.Merge(m, src)
}
func (m *GetResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_GetResponseMetadata.Size(m)
}
func (m *GetResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponseMetadata proto.InternalMessageInfo

func (m *GetResponseMetadata) GetFound() int64 {
	if m != nil {
		return m.Found
	}
	return 0
}

// UpdateRequestMetadata
type UpdateRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequestMetadata) Reset()         { *m = UpdateRequestMetadata{} }
func (m *UpdateRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*UpdateRequestMetadata) ProtoMessage()    {}
func (*UpdateRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{5}
}

func (m *UpdateRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequestMetadata.Unmarshal(m, b)
}
func (m *UpdateRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequestMetadata.Marshal(b, m, deterministic)
}
func (m *UpdateRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequestMetadata.Merge(m, src)
}
func (m *UpdateRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_UpdateRequestMetadata.Size(m)
}
func (m *UpdateRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequestMetadata proto.InternalMessageInfo

// UpdateResponseMetadata
type UpdateResponseMetadata struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponseMetadata) Reset()         { *m = UpdateResponseMetadata{} }
func (m *UpdateResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*UpdateResponseMetadata) ProtoMessage()    {}
func (*UpdateResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{6}
}

func (m *UpdateResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponseMetadata.Unmarshal(m, b)
}
func (m *UpdateResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponseMetadata.Marshal(b, m, deterministic)
}
func (m *UpdateResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponseMetadata.Merge(m, src)
}
func (m *UpdateResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_UpdateResponseMetadata.Size(m)
}
func (m *UpdateResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponseMetadata proto.InternalMessageInfo

func (m *UpdateResponseMetadata) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

// DeleteRequestMetadata
type DeleteRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequestMetadata) Reset()         { *m = DeleteRequestMetadata{} }
func (m *DeleteRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*DeleteRequestMetadata) ProtoMessage()    {}
func (*DeleteRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{7}
}

func (m *DeleteRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequestMetadata.Unmarshal(m, b)
}
func (m *DeleteRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequestMetadata.Marshal(b, m, deterministic)
}
func (m *DeleteRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequestMetadata.Merge(m, src)
}
func (m *DeleteRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_DeleteRequestMetadata.Size(m)
}
func (m *DeleteRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequestMetadata proto.InternalMessageInfo

// DeleteResponseMetadata
type DeleteResponseMetadata struct {
	Affected             int64    `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponseMetadata) Reset()         { *m = DeleteResponseMetadata{} }
func (m *DeleteResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*DeleteResponseMetadata) ProtoMessage()    {}
func (*DeleteResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{8}
}

func (m *DeleteResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponseMetadata.Unmarshal(m, b)
}
func (m *DeleteResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponseMetadata.Marshal(b, m, deterministic)
}
func (m *DeleteResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponseMetadata.Merge(m, src)
}
func (m *DeleteResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_DeleteResponseMetadata.Size(m)
}
func (m *DeleteResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponseMetadata proto.InternalMessageInfo

func (m *DeleteResponseMetadata) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

// BatchUpdateRequestMetadata
type BatchUpdateRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchUpdateRequestMetadata) Reset()         { *m = BatchUpdateRequestMetadata{} }
func (m *BatchUpdateRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchUpdateRequestMetadata) ProtoMessage()    {}
func (*BatchUpdateRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{9}
}

func (m *BatchUpdateRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpdateRequestMetadata.Unmarshal(m, b)
}
func (m *BatchUpdateRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpdateRequestMetadata.Marshal(b, m, deterministic)
}
func (m *BatchUpdateRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpdateRequestMetadata.Merge(m, src)
}
func (m *BatchUpdateRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchUpdateRequestMetadata.Size(m)
}
func (m *BatchUpdateRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpdateRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpdateRequestMetadata proto.InternalMessageInfo

// BatchUpdateResponseMetadata
type BatchUpdateResponseMetadata struct {
	Found                int64    `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Affected             int64    `protobuf:"varint,2,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchUpdateResponseMetadata) Reset()         { *m = BatchUpdateResponseMetadata{} }
func (m *BatchUpdateResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchUpdateResponseMetadata) ProtoMessage()    {}
func (*BatchUpdateResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{10}
}

func (m *BatchUpdateResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUpdateResponseMetadata.Unmarshal(m, b)
}
func (m *BatchUpdateResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUpdateResponseMetadata.Marshal(b, m, deterministic)
}
func (m *BatchUpdateResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUpdateResponseMetadata.Merge(m, src)
}
func (m *BatchUpdateResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchUpdateResponseMetadata.Size(m)
}
func (m *BatchUpdateResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUpdateResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUpdateResponseMetadata proto.InternalMessageInfo

func (m *BatchUpdateResponseMetadata) GetFound() int64 {
	if m != nil {
		return m.Found
	}
	return 0
}

func (m *BatchUpdateResponseMetadata) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

// BatchDeleteRequestMetadata
type BatchDeleteRequestMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDeleteRequestMetadata) Reset()         { *m = BatchDeleteRequestMetadata{} }
func (m *BatchDeleteRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchDeleteRequestMetadata) ProtoMessage()    {}
func (*BatchDeleteRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{11}
}

func (m *BatchDeleteRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDeleteRequestMetadata.Unmarshal(m, b)
}
func (m *BatchDeleteRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDeleteRequestMetadata.Marshal(b, m, deterministic)
}
func (m *BatchDeleteRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDeleteRequestMetadata.Merge(m, src)
}
func (m *BatchDeleteRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchDeleteRequestMetadata.Size(m)
}
func (m *BatchDeleteRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDeleteRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDeleteRequestMetadata proto.InternalMessageInfo

// BatchDeleteResponseMetadata
type BatchDeleteResponseMetadata struct {
	Found                int64    `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Affected             int64    `protobuf:"varint,2,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDeleteResponseMetadata) Reset()         { *m = BatchDeleteResponseMetadata{} }
func (m *BatchDeleteResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchDeleteResponseMetadata) ProtoMessage()    {}
func (*BatchDeleteResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{12}
}

func (m *BatchDeleteResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDeleteResponseMetadata.Unmarshal(m, b)
}
func (m *BatchDeleteResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDeleteResponseMetadata.Marshal(b, m, deterministic)
}
func (m *BatchDeleteResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDeleteResponseMetadata.Merge(m, src)
}
func (m *BatchDeleteResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchDeleteResponseMetadata.Size(m)
}
func (m *BatchDeleteResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDeleteResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDeleteResponseMetadata proto.InternalMessageInfo

func (m *BatchDeleteResponseMetadata) GetFound() int64 {
	if m != nil {
		return m.Found
	}
	return 0
}

func (m *BatchDeleteResponseMetadata) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

// ListRequestMetadata
type ListRequestMetadata struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequestMetadata) Reset()         { *m = ListRequestMetadata{} }
func (m *ListRequestMetadata) String() string { return proto.CompactTextString(m) }
func (*ListRequestMetadata) ProtoMessage()    {}
func (*ListRequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{13}
}

func (m *ListRequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequestMetadata.Unmarshal(m, b)
}
func (m *ListRequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequestMetadata.Marshal(b, m, deterministic)
}
func (m *ListRequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequestMetadata.Merge(m, src)
}
func (m *ListRequestMetadata) XXX_Size() int {
	return xxx_messageInfo_ListRequestMetadata.Size(m)
}
func (m *ListRequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequestMetadata proto.InternalMessageInfo

func (m *ListRequestMetadata) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

// ListResponseMetadata
type ListResponseMetadata struct {
	NextPage             string   `protobuf:"bytes,1,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	Found                int64    `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponseMetadata) Reset()         { *m = ListResponseMetadata{} }
func (m *ListResponseMetadata) String() string { return proto.CompactTextString(m) }
func (*ListResponseMetadata) ProtoMessage()    {}
func (*ListResponseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{14}
}

func (m *ListResponseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponseMetadata.Unmarshal(m, b)
}
func (m *ListResponseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponseMetadata.Marshal(b, m, deterministic)
}
func (m *ListResponseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponseMetadata.Merge(m, src)
}
func (m *ListResponseMetadata) XXX_Size() int {
	return xxx_messageInfo_ListResponseMetadata.Size(m)
}
func (m *ListResponseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponseMetadata proto.InternalMessageInfo

func (m *ListResponseMetadata) GetNextPage() string {
	if m != nil {
		return m.NextPage
	}
	return ""
}

func (m *ListResponseMetadata) GetFound() int64 {
	if m != nil {
		return m.Found
	}
	return 0
}

func init() {
	proto.RegisterType((*ErrorDetail)(nil), "v1.ErrorDetail")
	proto.RegisterType((*CreateRequestMetadata)(nil), "v1.CreateRequestMetadata")
	proto.RegisterType((*CreateResponseMetadata)(nil), "v1.CreateResponseMetadata")
	proto.RegisterType((*GetRequestMetadata)(nil), "v1.GetRequestMetadata")
	proto.RegisterType((*GetResponseMetadata)(nil), "v1.GetResponseMetadata")
	proto.RegisterType((*UpdateRequestMetadata)(nil), "v1.UpdateRequestMetadata")
	proto.RegisterType((*UpdateResponseMetadata)(nil), "v1.UpdateResponseMetadata")
	proto.RegisterType((*DeleteRequestMetadata)(nil), "v1.DeleteRequestMetadata")
	proto.RegisterType((*DeleteResponseMetadata)(nil), "v1.DeleteResponseMetadata")
	proto.RegisterType((*BatchUpdateRequestMetadata)(nil), "v1.BatchUpdateRequestMetadata")
	proto.RegisterType((*BatchUpdateResponseMetadata)(nil), "v1.BatchUpdateResponseMetadata")
	proto.RegisterType((*BatchDeleteRequestMetadata)(nil), "v1.BatchDeleteRequestMetadata")
	proto.RegisterType((*BatchDeleteResponseMetadata)(nil), "v1.BatchDeleteResponseMetadata")
	proto.RegisterType((*ListRequestMetadata)(nil), "v1.ListRequestMetadata")
	proto.RegisterType((*ListResponseMetadata)(nil), "v1.ListResponseMetadata")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_423806180556987f) }

var fileDescriptor_423806180556987f = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x52, 0x4a, 0xe8, 0x20, 0x24, 0xb4, 0x4d, 0x48, 0x15, 0x7a, 0xd8, 0xfa, 0x40, 0x41,
	0x22, 0x31, 0x85, 0x5b, 0xb9, 0xd0, 0x24, 0x50, 0x81, 0xd2, 0x12, 0xa5, 0x70, 0x46, 0x5b, 0x67,
	0x62, 0x5b, 0xc4, 0xbb, 0xcb, 0xee, 0x18, 0x97, 0x87, 0xe0, 0x00, 0x4f, 0xc1, 0xb1, 0x52, 0xdf,
	0x0c, 0x2e, 0x88, 0x13, 0xb2, 0x8d, 0x49, 0x1d, 0x19, 0x41, 0xa5, 0x72, 0x4a, 0xfc, 0x7d, 0xb3,
	0xdf, 0xcf, 0x6a, 0x6c, 0x00, 0xab, 0xd1, 0xeb, 0x69, 0xa3, 0x48, 0xb1, 0xfa, 0xfb, 0x9d, 0xce,
	0x0d, 0xa5, 0x29, 0x54, 0xd2, 0xe6, 0x50, 0xe7, 0x7e, 0xf6, 0xe3, 0x75, 0x7d, 0x94, 0x5d, 0x9b,
	0x08, 0xdf, 0x47, 0xe3, 0xfe, 0x9a, 0x70, 0x85, 0x94, 0x8a, 0xc4, 0xb9, 0x69, 0x67, 0x1b, 0xae,
	0x3f, 0x35, 0x46, 0x99, 0x21, 0x92, 0x08, 0xe7, 0x6c, 0x03, 0x1a, 0x11, 0x5a, 0x2b, 0x7c, 0xdc,
	0xa8, 0xf1, 0xda, 0xdd, 0xb5, 0x49, 0xf1, 0xe8, 0xb4, 0xa1, 0x35, 0x30, 0x28, 0x08, 0x27, 0xf8,
	0x2e, 0x46, 0x4b, 0x07, 0x48, 0x62, 0x2a, 0x48, 0x38, 0x23, 0xb8, 0x55, 0x10, 0x56, 0x2b, 0x69,
	0xb1, 0x60, 0xd8, 0x1d, 0xb8, 0x26, 0x66, 0x33, 0xf4, 0x08, 0xa7, 0x99, 0xda, 0x4a, 0x1f, 0xbe,
	0x7e, 0x3f, 0x6b, 0xac, 0x9e, 0x7e, 0x3b, 0x6b, 0xd4, 0x26, 0xbf, 0xb9, 0x5d, 0xf8, 0x91, 0xa2,
	0x5f, 0x52, 0xd4, 0x69, 0x02, 0xdb, 0x47, 0x5a, 0xf6, 0x18, 0xc0, 0x7a, 0x86, 0x2e, 0x19, 0x70,
	0x58, 0x9d, 0xa9, 0x58, 0x56, 0xa9, 0xe7, 0x44, 0x49, 0xba, 0x0d, 0xad, 0xd7, 0x7a, 0x5a, 0xdd,
	0xa0, 0x20, 0x2e, 0xa1, 0x41, 0x1b, 0x5a, 0x43, 0x9c, 0x63, 0xa5, 0x4d, 0x41, 0x5c, 0x82, 0xcd,
	0x26, 0x74, 0xfa, 0x82, 0xbc, 0xa0, 0xba, 0x92, 0x85, 0xdb, 0x25, 0xf6, 0xa2, 0x17, 0x57, 0x8a,
	0x54, 0xbf, 0x60, 0xa4, 0xea, 0xfa, 0x45, 0xa4, 0x3f, 0xdc, 0xc1, 0xff, 0x89, 0x74, 0x0f, 0xd6,
	0x47, 0xa1, 0x5d, 0xde, 0x27, 0xc6, 0xe0, 0x8a, 0x5e, 0xec, 0x78, 0xf6, 0xdf, 0x89, 0xa0, 0x99,
	0x8f, 0x2e, 0x05, 0xdb, 0x86, 0x35, 0x89, 0x27, 0xf4, 0x66, 0x71, 0xa0, 0xec, 0x9b, 0x92, 0x63,
	0xe1, 0xe3, 0xa2, 0x41, 0xfd, 0x1f, 0xb6, 0xb1, 0xff, 0xa9, 0xfe, 0x79, 0xef, 0x63, 0x9d, 0x9d,
	0xd6, 0x60, 0xd3, 0x9f, 0x8c, 0x07, 0xee, 0x8b, 0xa3, 0x97, 0x87, 0x7c, 0x5f, 0x10, 0x26, 0xe2,
	0x03, 0x7f, 0x85, 0x5e, 0xc0, 0x8f, 0x74, 0xf8, 0x16, 0xd9, 0x63, 0x21, 0x39, 0x9e, 0xe8, 0xb9,
	0x32, 0xd9, 0x7b, 0xcb, 0xd5, 0x8c, 0x07, 0x2a, 0xe1, 0x21, 0xf1, 0x19, 0xe2, 0xdc, 0x72, 0x52,
	0x3c, 0xb6, 0xc8, 0x29, 0x40, 0x9e, 0xea, 0xf0, 0x4c, 0xc7, 0xcf, 0x75, 0x9c, 0x43, 0x60, 0x29,
	0xd8, 0x2d, 0x74, 0x6d, 0x26, 0xe9, 0x04, 0x44, 0xda, 0xee, 0xba, 0x6e, 0x92, 0x24, 0x3d, 0x4b,
	0x46, 0x49, 0x7f, 0x1a, 0xf5, 0x3c, 0x15, 0xb9, 0x53, 0xe5, 0x59, 0x57, 0xe8, 0xd0, 0xed, 0x34,
	0x6d, 0xac, 0xb5, 0x32, 0xf4, 0xe4, 0x3c, 0xff, 0x70, 0x65, 0xa7, 0xf7, 0xa0, 0x73, 0x53, 0x68,
	0x5d, 0x3a, 0x66, 0x9e, 0xc1, 0xd6, 0x08, 0x85, 0x91, 0x3c, 0x52, 0x06, 0xb9, 0x38, 0x56, 0x31,
	0x65, 0x81, 0xf2, 0xa1, 0xe1, 0x01, 0xdf, 0x1b, 0x3f, 0x67, 0x5b, 0x7f, 0x75, 0x3d, 0xbe, 0x9a,
	0x7d, 0x93, 0x1e, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x8a, 0x7f, 0x9d, 0xe2, 0x04, 0x00,
	0x00,
}
