// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tags.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Tags defines a custom message that will translate from a slice of
// Pairs into a map[] in each supported language.  See options.proto for
// documentation on the custom message options.
type Tags struct {
	Pairs                []*Tags_Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{0}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetPairs() []*Tags_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Tags_Pair struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tags_Pair) Reset()         { *m = Tags_Pair{} }
func (m *Tags_Pair) String() string { return proto.CompactTextString(m) }
func (*Tags_Pair) ProtoMessage()    {}
func (*Tags_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{0, 0}
}

func (m *Tags_Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags_Pair.Unmarshal(m, b)
}
func (m *Tags_Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags_Pair.Marshal(b, m, deterministic)
}
func (m *Tags_Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags_Pair.Merge(m, src)
}
func (m *Tags_Pair) XXX_Size() int {
	return xxx_messageInfo_Tags_Pair.Size(m)
}
func (m *Tags_Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Tags_Pair proto.InternalMessageInfo

func (m *Tags_Pair) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tags_Pair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Tags)(nil), "v1.Tags")
	proto.RegisterType((*Tags_Pair)(nil), "v1.Tags.Pair")
}

func init() { proto.RegisterFile("tags.proto", fileDescriptor_e7d9cbcae1e528f6) }

var fileDescriptor_e7d9cbcae1e528f6 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x4c, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0xe2, 0xcd, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x83, 0x0a, 0x29, 0xad, 0x64, 0xe4, 0x62, 0x09, 0x49, 0x4c, 0x2f, 0x16, 0x52, 0xe6,
	0x62, 0x2d, 0x48, 0xcc, 0x2c, 0x2a, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd5, 0x2b,
	0x33, 0xd4, 0x03, 0x49, 0xe8, 0x05, 0x24, 0x66, 0x16, 0x05, 0x41, 0xe4, 0xa4, 0x0c, 0xb8, 0x58,
	0x40, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x08,
	0xe1, 0x58, 0x79, 0xfd, 0xfa, 0xb1, 0x99, 0xdd, 0xf5, 0xd4, 0xe7, 0xcd, 0xec, 0x0e, 0xaf, 0x3e,
	0x6f, 0x66, 0x67, 0x01, 0xb9, 0xe6, 0x13, 0x88, 0x01, 0x32, 0xfb, 0xd7, 0xe7, 0xcd, 0xec, 0xb2,
	0x59, 0x89, 0x65, 0x89, 0x7a, 0xa5, 0x25, 0x99, 0x39, 0x7a, 0xbe, 0x89, 0x05, 0x36, 0xc1, 0x25,
	0x45, 0x99, 0x79, 0xe9, 0x3a, 0x0a, 0x10, 0xda, 0xae, 0xe9, 0xcb, 0x66, 0x76, 0xf6, 0x90, 0xca,
	0x82, 0x54, 0xdf, 0xc4, 0x02, 0x27, 0x1d, 0x2e, 0x99, 0xe4, 0xfc, 0x5c, 0xbd, 0xe2, 0x92, 0xa2,
	0xfc, 0xbc, 0xf4, 0x94, 0x5c, 0xbd, 0xc4, 0x82, 0x4c, 0x90, 0x2b, 0x0b, 0x72, 0x4a, 0x73, 0x93,
	0x32, 0xf3, 0xd2, 0x9d, 0x78, 0x40, 0x66, 0x06, 0x40, 0x79, 0x49, 0x6c, 0x60, 0x0f, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xda, 0xe2, 0x2d, 0x01, 0x01, 0x00, 0x00,
}
